comment: false
codecov:
  branch: master

coverage:
  precision: 2
  status:
    patch: off
    project:
      default:
        target: 93.9%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "tests"