"""Request Common Models. These are only for internal module use."""
# pylint: disable=invalid-name, too-many-instance-attributes, line-too-long, too-many-lines
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime

import attr

from .base import BaseModel
from .const import ProtocolType


@dataclass(init=False)
class _SelectOption(BaseModel):
    """Select option attributes."""

    name: str = attr.ib(type=str)
    order: int = attr.ib(type=int)
    value: str | list[str] | int = attr.ib(type=int)


@dataclass(init=False)
class _SelectOptionExtended(_SelectOption):
    """Select options extended attributes."""

    dividerAfter: bool = attr.ib(type=bool)


@dataclass(init=False)
class _Fields(_SelectOption):
    """Fields attributes."""

    advanced: bool = attr.ib(type=bool)
    errors: list = attr.ib(type=list)
    helpText: str = attr.ib(type=str)
    hidden: str = attr.ib(type=str)
    label: str = attr.ib(type=str)
    pending: bool = attr.ib(type=bool)
    selectOptions: list[_SelectOptionExtended] | None = None
    type: str = attr.ib(type=str)
    warnings: list = attr.ib(type=list)

    def __post_init__(self):
        self.selectOptions = [
            _SelectOptionExtended(opt) for opt in self.selectOptions or []
        ]


@dataclass(init=False)
class _Common(BaseModel):
    """Common attributes."""

    fields: list[_Fields] | None = None
    implementation: str = attr.ib(type=str)
    implementationName: str = attr.ib(type=str)
    infoLink: str = attr.ib(type=str)
    name: str = attr.ib(type=str)

    def __post_init__(self):
        self.fields = [_Fields(field) for field in self.fields or []]


@dataclass(init=False)
class _Common2(BaseModel):
    """Common attributes."""

    downloadId: str = attr.ib(type=str)
    eventType: str = attr.ib(type=str)


@dataclass(init=False)
class _Common3(BaseModel):
    """Common attributes."""

    id: int = attr.ib(type=int)
    name: str = attr.ib(type=str)


@dataclass(init=False)
class _Common4(BaseModel):
    """Common attributes."""

    downloadClient: str = attr.ib(type=str)
    downloadId: str = attr.ib(type=str)
    estimatedCompletionTime: datetime = attr.ib(type=datetime)
    indexer: str = attr.ib(type=str)
    outputPath: str = attr.ib(type=str)


@dataclass(init=False)
class _Common5(BaseModel):
    """Common attributes."""

    coverType: str = attr.ib(type=str)
    url: str = attr.ib(type=str)


@dataclass(init=False)
class _Common6(BaseModel):
    """Common attributes."""

    monitored: bool = attr.ib(type=bool)
    overview: str = attr.ib(type=str)


@dataclass(init=False)
class _Common7(BaseModel):
    """Common attributes."""

    id: int = attr.ib(type=int)
    indexer: str = attr.ib(type=str)
    protocol: ProtocolType = attr.ib(type=ProtocolType)


@dataclass(init=False)
class _QualityInfo(_Common3):
    """Quality info attributes."""

    modifier: str = attr.ib(type=str)
    resolution: int = attr.ib(type=int)
    source: str = attr.ib(type=str)


@dataclass(init=False)
class _Revision(BaseModel):
    """Revision attributes."""

    isRepack: bool = attr.ib(type=bool)
    real: int = attr.ib(type=int)
    version: int = attr.ib(type=int)


@dataclass(init=False)
class _Quality(BaseModel):
    """Quality attributes."""

    quality: _QualityInfo = attr.ib(type=_QualityInfo)
    revision: _Revision = attr.ib(type=_Revision)

    def __post_init__(self):
        """Post init."""
        self.quality = _QualityInfo(self.quality) or {}
        self.revision = _Revision(self.revision) or {}


@dataclass(init=False)
class _Common8(BaseModel):
    """Common attributes."""

    id: int = attr.ib(type=int)
    protocol: ProtocolType = attr.ib(type=ProtocolType)
    quality: _Quality = attr.ib(type=_Quality)
    size: int = attr.ib(type=int)
    sizeleft: int = attr.ib(type=int)
    status: str = attr.ib(type=str)
    statusMessages: list[_StatusMessage] | None = None
    timeleft: str = attr.ib(type=str)
    title: str = attr.ib(type=str)
    trackedDownloadState: str = attr.ib(type=str)
    trackedDownloadStatus: str = attr.ib(type=str)


@dataclass(init=False)
class _Common9(BaseModel):
    """Common attributes."""

    certification: str = attr.ib(type=str)
    genres: list[str] = attr.ib(type='list[str]')
    imdbId: str = attr.ib(type=str)
    runtime: int = attr.ib(type=int)
    title: str = attr.ib(type=str)
    year: int = attr.ib(type=int)


@dataclass(init=False)
class _CommonAttrs(BaseModel):
    """Common attributes."""

    audioBitrate: str = attr.ib(type=str)
    audioChannels: float = attr.ib(type=float)
    audioCodec: str = attr.ib(type=str)
    audioLanguages: str = attr.ib(type=str)
    audioStreamCount: int = attr.ib(type=int)
    resolution: str = attr.ib(type=str)
    runTime: str = attr.ib(type=str)
    scanType: str = attr.ib(type=str)
    subtitles: str = attr.ib(type=str)
    videoBitDepth: int = attr.ib(type=int)
    videoBitrate: int = attr.ib(type=int)
    videoCodec: str = attr.ib(type=str)
    videoDynamicRangeType: str = attr.ib(type=str)
    videoFps: float = attr.ib(type=float)


@dataclass(init=False)
class _CommandBody(BaseModel):
    """Command body attributes."""

    completionMessage: str = attr.ib(type=str)
    isExclusive: bool = attr.ib(type=bool)
    isNewMovie: bool = attr.ib(type=bool)
    isTypeExclusive: bool = attr.ib(type=bool)
    lastExecutionTime: datetime = attr.ib(type=datetime)
    lastStartTime: datetime = attr.ib(type=datetime)
    name: str = attr.ib(type=str)
    requiresDiskAccess: bool = attr.ib(type=bool)
    sendUpdatesToClient: bool = attr.ib(type=bool)
    suppressMessages: bool = attr.ib(type=bool)
    trigger: str = attr.ib(type=str)
    updateScheduledTask: bool = attr.ib(type=bool)


@dataclass(init=False)
class _CustomFilterAttr(BaseModel):
    """Custom filter attributes."""

    key: str = attr.ib(type=str)
    type: str = attr.ib(type=str)
    value: list[str] = attr.ib(type='list[str]')


@dataclass(init=False)
class _MetadataFields(_Fields):
    """Metadata fields attributes."""

    section: str = attr.ib(type=str)


@dataclass(init=False)
class _FilesystemFolder(BaseModel):
    """Filesystem folder attributes."""

    name: str = attr.ib(type=str)
    path: str = attr.ib(type=str)


@dataclass(init=False)
class _FilesystemDirectory(_FilesystemFolder):
    """Filesystem directory attributes."""

    lastModified: datetime = attr.ib(type=datetime)
    size: int = attr.ib(type=int)
    type: str = attr.ib(type=str)


@dataclass(init=False)
class _ImportListCommon(_FilesystemFolder):
    """Import list common attributes."""

    configContract: str = attr.ib(type=str)
    listOrder: int = attr.ib(type=int)
    rootFolderPath: str = attr.ib(type=str)


@dataclass(init=False)
class _LocalizationStrings(BaseModel):
    """Localization strings attributes."""

    About: str = attr.ib(type=str)
    Absolute: str = attr.ib(type=str)
    AcceptConfirmationModal: str = attr.ib(type=str)
    Actions: str = attr.ib(type=str)
    Activity: str = attr.ib(type=str)
    Add: str = attr.ib(type=str)
    AddCustomFormat: str = attr.ib(type=str)
    AddDelayProfile: str = attr.ib(type=str)
    AddDownloadClient: str = attr.ib(type=str)
    Added: str = attr.ib(type=str)
    AddedAuthorSettings: str = attr.ib(type=str)
    AddedToDownloadQueue: str = attr.ib(type=str)
    AddExclusion: str = attr.ib(type=str)
    AddImportListExclusionHelpText: str = attr.ib(type=str)
    AddIndexer: str = attr.ib(type=str)
    AddingTag: str = attr.ib(type=str)
    AddList: str = attr.ib(type=str)
    AddListExclusion: str = attr.ib(type=str)
    AddMissing: str = attr.ib(type=str)
    AddMovie: str = attr.ib(type=str)
    AddMovies: str = attr.ib(type=str)
    AddMoviesMonitored: str = attr.ib(type=str)
    AddNew: str = attr.ib(type=str)
    AddNewItem: str = attr.ib(type=str)
    AddNewMessage: str = attr.ib(type=str)
    AddNewMovie: str = attr.ib(type=str)
    AddNewTmdbIdMessage: str = attr.ib(type=str)
    AddNotification: str = attr.ib(type=str)
    AddQualityProfile: str = attr.ib(type=str)
    AddRemotePathMapping: str = attr.ib(type=str)
    AddRestriction: str = attr.ib(type=str)
    AddRootFolder: str = attr.ib(type=str)
    AddToDownloadQueue: str = attr.ib(type=str)
    AdvancedSettingsHiddenClickToShow: str = attr.ib(type=str)
    AdvancedSettingsShownClickToHide: str = attr.ib(type=str)
    AfterManualRefresh: str = attr.ib(type=str)
    Age: str = attr.ib(type=str)
    Agenda: str = attr.ib(type=str)
    AgeWhenGrabbed: str = attr.ib(type=str)
    All: str = attr.ib(type=str)
    AllAuthorBooks: str = attr.ib(type=str)
    AllBooks: str = attr.ib(type=str)
    AllExpandedCollapseAll: str = attr.ib(type=str)
    AllExpandedExpandAll: str = attr.ib(type=str)
    AllFiles: str = attr.ib(type=str)
    AllMoviesHiddenDueToFilter: str = attr.ib(type=str)
    AllMoviesInPathHaveBeenImported: str = attr.ib(type=str)
    AllowAuthorChangeClickToChangeAuthor: str = attr.ib(type=str)
    AllowedLanguages: str = attr.ib(type=str)
    AllowFingerprinting: str = attr.ib(type=str)
    AllowFingerprintingHelpText: str = attr.ib(type=str)
    AllowFingerprintingHelpTextWarning: str = attr.ib(type=str)
    AllowHardcodedSubs: str = attr.ib(type=str)
    AllowHardcodedSubsHelpText: str = attr.ib(type=str)
    AllResultsHiddenFilter: str = attr.ib(type=str)
    AlreadyInYourLibrary: str = attr.ib(type=str)
    AlternateTitles: str = attr.ib(type=str)
    AlternateTitleslength1Title: str = attr.ib(type=str)
    AlternateTitleslength1Titles: str = attr.ib(type=str)
    AlternativeTitle: str = attr.ib(type=str)
    Always: str = attr.ib(type=str)
    AnalyseVideoFiles: str = attr.ib(type=str)
    Analytics: str = attr.ib(type=str)
    AnalyticsEnabledHelpText: str = attr.ib(type=str)
    AnalyticsEnabledHelpTextWarning: str = attr.ib(type=str)
    Announced: str = attr.ib(type=str)
    AnnouncedMsg: str = attr.ib(type=str)
    AnyEditionOkHelpText: str = attr.ib(type=str)
    ApiKey: str = attr.ib(type=str)
    APIKey: str = attr.ib(type=str)
    ApiKeyHelpTextWarning: str = attr.ib(type=str)
    AppDataDirectory: str = attr.ib(type=str)
    AppDataLocationHealthCheckMessage: str = attr.ib(type=str)
    Apply: str = attr.ib(type=str)
    ApplyTags: str = attr.ib(type=str)
    ApplyTagsHelpTexts1: str = attr.ib(type=str)
    ApplyTagsHelpTexts2: str = attr.ib(type=str)
    ApplyTagsHelpTexts3: str = attr.ib(type=str)
    ApplyTagsHelpTexts4: str = attr.ib(type=str)
    AptUpdater: str = attr.ib(type=str)
    AreYouSureYouWantToDeleteFormat: str = attr.ib(type=str)
    AreYouSureYouWantToDeleteThisDelayProfile: str = attr.ib(type=str)
    AreYouSureYouWantToDeleteThisImportListExclusion: str = attr.ib(type=str)
    AreYouSureYouWantToDeleteThisRemotePathMapping: str = attr.ib(type=str)
    AreYouSureYouWantToRemoveSelectedItemFromQueue: str = attr.ib(type=str)
    AreYouSureYouWantToRemoveSelectedItemsFromQueue: str = attr.ib(type=str)
    AreYouSureYouWantToRemoveTheSelectedItemsFromBlocklist: str = attr.ib(type=str)
    AreYouSureYouWantToResetYourAPIKey: str = attr.ib(type=str)
    AsAllDayHelpText: str = attr.ib(type=str)
    ASIN: str = attr.ib(type=str)
    AudioFileMetadata: str = attr.ib(type=str)
    AudioInfo: str = attr.ib(type=str)
    AuthBasic: str = attr.ib(type=str)
    Authentication: str = attr.ib(type=str)
    AuthenticationMethodHelpText: str = attr.ib(type=str)
    AuthForm: str = attr.ib(type=str)
    Author: str = attr.ib(type=str)
    AuthorClickToChangeBook: str = attr.ib(type=str)
    AuthorEditor: str = attr.ib(type=str)
    AuthorFolderFormat: str = attr.ib(type=str)
    AuthorIndex: str = attr.ib(type=str)
    AuthorNameHelpText: str = attr.ib(type=str)
    Authors: str = attr.ib(type=str)
    Automatic: str = attr.ib(type=str)
    AutomaticallySwitchEdition: str = attr.ib(type=str)
    AutomaticSearch: str = attr.ib(type=str)
    AutoRedownloadFailedHelpText: str = attr.ib(type=str)
    AutoUnmonitorPreviouslyDownloadedBooksHelpText: str = attr.ib(type=str)
    AutoUnmonitorPreviouslyDownloadedMoviesHelpText: str = attr.ib(type=str)
    AvailabilityDelay: str = attr.ib(type=str)
    AvailabilityDelayHelpText: str = attr.ib(type=str)
    Backup: str = attr.ib(type=str)
    BackupFolderHelpText: str = attr.ib(type=str)
    BackupIntervalHelpText: str = attr.ib(type=str)
    BackupNow: str = attr.ib(type=str)
    BackupRetentionHelpText: str = attr.ib(type=str)
    Backups: str = attr.ib(type=str)
    BeforeUpdate: str = attr.ib(type=str)
    BindAddress: str = attr.ib(type=str)
    BindAddressHelpText: str = attr.ib(type=str)
    BindAddressHelpTextWarning: str = attr.ib(type=str)
    Blocklist: str = attr.ib(type=str)
    Blocklisted: str = attr.ib(type=str)
    BlocklistHelpText: str = attr.ib(type=str)
    BlocklistRelease: str = attr.ib(type=str)
    BlocklistReleases: str = attr.ib(type=str)
    Book: str = attr.ib(type=str)
    BookAvailableButMissing: str = attr.ib(type=str)
    BookDownloaded: str = attr.ib(type=str)
    BookEditor: str = attr.ib(type=str)
    BookFileCountBookCountTotalTotalBookCountInterp: str = attr.ib(type=str)
    BookFileCounttotalBookCountBooksDownloadedInterp: str = attr.ib(type=str)
    BookFilesCountMessage: str = attr.ib(type=str)
    BookHasNotAired: str = attr.ib(type=str)
    BookIndex: str = attr.ib(type=str)
    BookIsDownloading: str = attr.ib(type=str)
    BookIsDownloadingInterp: str = attr.ib(type=str)
    BookIsNotMonitored: str = attr.ib(type=str)
    BookList: str = attr.ib(type=str)
    BookMissingFromDisk: str = attr.ib(type=str)
    BookMonitoring: str = attr.ib(type=str)
    BookNaming: str = attr.ib(type=str)
    Books: str = attr.ib(type=str)
    BooksTotal: str = attr.ib(type=str)
    BookStudio: str = attr.ib(type=str)
    BookTitle: str = attr.ib(type=str)
    Branch: str = attr.ib(type=str)
    BranchUpdate: str = attr.ib(type=str)
    BranchUpdateMechanism: str = attr.ib(type=str)
    BuiltIn: str = attr.ib(type=str)
    BypassDelayIfHighestQuality: str = attr.ib(type=str)
    BypassDelayIfHighestQualityHelpText: str = attr.ib(type=str)
    BypassProxyForLocalAddresses: str = attr.ib(type=str)
    Calendar: str = attr.ib(type=str)
    CalendarOptions: str = attr.ib(type=str)
    CalendarWeekColumnHeaderHelpText: str = attr.ib(type=str)
    CalibreContentServer: str = attr.ib(type=str)
    CalibreContentServerText: str = attr.ib(type=str)
    CalibreHost: str = attr.ib(type=str)
    CalibreLibrary: str = attr.ib(type=str)
    CalibreMetadata: str = attr.ib(type=str)
    CalibreNotCalibreWeb: str = attr.ib(type=str)
    CalibreOutputFormat: str = attr.ib(type=str)
    CalibreOutputProfile: str = attr.ib(type=str)
    CalibrePassword: str = attr.ib(type=str)
    CalibrePort: str = attr.ib(type=str)
    CalibreSettings: str = attr.ib(type=str)
    CalibreUrlBase: str = attr.ib(type=str)
    CalibreUsername: str = attr.ib(type=str)
    Cancel: str = attr.ib(type=str)
    CancelMessageText: str = attr.ib(type=str)
    CancelPendingTask: str = attr.ib(type=str)
    CancelProcessing: str = attr.ib(type=str)
    CantFindMovie: str = attr.ib(type=str)
    Cast: str = attr.ib(type=str)
    CatalogNumber: str = attr.ib(type=str)
    CertificateValidation: str = attr.ib(type=str)
    CertificateValidationHelpText: str = attr.ib(type=str)
    Certification: str = attr.ib(type=str)
    CertificationCountry: str = attr.ib(type=str)
    CertificationCountryHelpText: str = attr.ib(type=str)
    CertValidationNoLocal: str = attr.ib(type=str)
    ChangeFileDate: str = attr.ib(type=str)
    ChangeHasNotBeenSavedYet: str = attr.ib(type=str)
    CheckDownloadClientForDetails: str = attr.ib(type=str)
    CheckForFinishedDownloadsInterval: str = attr.ib(type=str)
    ChmodFolder: str = attr.ib(type=str)
    ChmodFolderHelpText: str = attr.ib(type=str)
    ChmodFolderHelpTextWarning: str = attr.ib(type=str)
    ChmodGroup: str = attr.ib(type=str)
    ChmodGroupHelpText: str = attr.ib(type=str)
    ChmodGroupHelpTextWarning: str = attr.ib(type=str)
    ChooseAnotherFolder: str = attr.ib(type=str)
    ChownGroup: str = attr.ib(type=str)
    ChownGroupHelpText: str = attr.ib(type=str)
    ChownGroupHelpTextWarning: str = attr.ib(type=str)
    CleanLibraryLevel: str = attr.ib(type=str)
    Clear: str = attr.ib(type=str)
    ClickToChangeLanguage: str = attr.ib(type=str)
    ClickToChangeMovie: str = attr.ib(type=str)
    ClickToChangeQuality: str = attr.ib(type=str)
    ClickToChangeReleaseGroup: str = attr.ib(type=str)
    ClientPriority: str = attr.ib(type=str)
    CloneCustomFormat: str = attr.ib(type=str)
    CloneFormatTag: str = attr.ib(type=str)
    CloneIndexer: str = attr.ib(type=str)
    CloneProfile: str = attr.ib(type=str)
    Close: str = attr.ib(type=str)
    CloseCurrentModal: str = attr.ib(type=str)
    CollapseMultipleBooks: str = attr.ib(type=str)
    CollapseMultipleBooksHelpText: str = attr.ib(type=str)
    Collection: str = attr.ib(type=str)
    ColonReplacement: str = attr.ib(type=str)
    ColonReplacementFormatHelpText: str = attr.ib(type=str)
    Columns: str = attr.ib(type=str)
    CompletedDownloadHandling: str = attr.ib(type=str)
    Component: str = attr.ib(type=str)
    Conditions: str = attr.ib(type=str)
    Connect: str = attr.ib(type=str)
    Connection: str = attr.ib(type=str)
    ConnectionLost: str = attr.ib(type=str)
    ConnectionLostAutomaticMessage: str = attr.ib(type=str)
    ConnectionLostMessage: str = attr.ib(type=str)
    Connections: str = attr.ib(type=str)
    ConnectSettings: str = attr.ib(type=str)
    ConnectSettingsSummary: str = attr.ib(type=str)
    ConsideredAvailable: str = attr.ib(type=str)
    ConsoleLogLevel: str = attr.ib(type=str)
    Continuing: str = attr.ib(type=str)
    ContinuingAllBooksDownloaded: str = attr.ib(type=str)
    ContinuingMoreBooksAreExpected: str = attr.ib(type=str)
    ContinuingNoAdditionalBooksAreExpected: str = attr.ib(type=str)
    CopyToClipboard: str = attr.ib(type=str)
    CopyUsingHardlinksHelpText: str = attr.ib(type=str)
    CopyUsingHardlinksHelpTextWarning: str = attr.ib(type=str)
    CouldNotConnectSignalR: str = attr.ib(type=str)
    CouldNotFindResults: str = attr.ib(type=str)
    Country: str = attr.ib(type=str)
    CreateEmptyAuthorFolders: str = attr.ib(type=str)
    CreateEmptyAuthorFoldersHelpText: str = attr.ib(type=str)
    CreateEmptyMovieFolders: str = attr.ib(type=str)
    CreateEmptyMovieFoldersHelpText: str = attr.ib(type=str)
    CreateGroup: str = attr.ib(type=str)
    Crew: str = attr.ib(type=str)
    CurrentlyInstalled: str = attr.ib(type=str)
    Custom: str = attr.ib(type=str)
    CustomFilters: str = attr.ib(type=str)
    CustomFormat: str = attr.ib(type=str)
    CustomFormatHelpText: str = attr.ib(type=str)
    CustomFormatJSON: str = attr.ib(type=str)
    CustomFormats: str = attr.ib(type=str)
    CustomFormatScore: str = attr.ib(type=str)
    CustomFormatsSettings: str = attr.ib(type=str)
    CustomFormatsSettingsSummary: str = attr.ib(type=str)
    CustomFormatUnknownCondition: str = attr.ib(type=str)
    CustomFormatUnknownConditionOption: str = attr.ib(type=str)
    Cutoff: str = attr.ib(type=str)
    CutoffFormatScoreHelpText: str = attr.ib(type=str)
    CutoffHelpText: str = attr.ib(type=str)
    CutoffUnmet: str = attr.ib(type=str)
    Date: str = attr.ib(type=str)
    Dates: str = attr.ib(type=str)
    Day: str = attr.ib(type=str)
    Days: str = attr.ib(type=str)
    DBMigration: str = attr.ib(type=str)
    Debug: str = attr.ib(type=str)
    DefaultCase: str = attr.ib(type=str)
    DefaultDelayProfile: str = attr.ib(type=str)
    DefaultMetadataProfileIdHelpText: str = attr.ib(type=str)
    DefaultMonitorOptionHelpText: str = attr.ib(type=str)
    DefaultQualityProfileIdHelpText: str = attr.ib(type=str)
    DefaultReadarrTags: str = attr.ib(type=str)
    DefaultTagsHelpText: str = attr.ib(type=str)
    DelayingDownloadUntilInterp: str = attr.ib(type=str)
    DelayProfile: str = attr.ib(type=str)
    DelayProfiles: str = attr.ib(type=str)
    Delete: str = attr.ib(type=str)
    DeleteBackup: str = attr.ib(type=str)
    DeleteBackupMessageText: str = attr.ib(type=str)
    DeleteBookFile: str = attr.ib(type=str)
    DeleteBookFileMessageText: str = attr.ib(type=str)
    DeleteCustomFormat: str = attr.ib(type=str)
    Deleted: str = attr.ib(type=str)
    DeleteDelayProfile: str = attr.ib(type=str)
    DeleteDelayProfileMessageText: str = attr.ib(type=str)
    DeletedMsg: str = attr.ib(type=str)
    DeleteDownloadClient: str = attr.ib(type=str)
    DeleteDownloadClientMessageText: str = attr.ib(type=str)
    DeleteEmptyFolders: str = attr.ib(type=str)
    DeleteEmptyFoldersHelpText: str = attr.ib(type=str)
    DeleteFile: str = attr.ib(type=str)
    DeleteFileLabel: str = attr.ib(type=str)
    DeleteFilesHelpText: str = attr.ib(type=str)
    DeleteFilesLabel: str = attr.ib(type=str)
    DeleteHeader: str = attr.ib(type=str)
    DeleteImportList: str = attr.ib(type=str)
    DeleteImportListExclusion: str = attr.ib(type=str)
    DeleteImportListExclusionMessageText: str = attr.ib(type=str)
    DeleteImportListMessageText: str = attr.ib(type=str)
    DeleteIndexer: str = attr.ib(type=str)
    DeleteIndexerMessageText: str = attr.ib(type=str)
    DeleteList: str = attr.ib(type=str)
    DeleteListMessageText: str = attr.ib(type=str)
    DeleteMetadataProfile: str = attr.ib(type=str)
    DeleteMetadataProfileMessageText: str = attr.ib(type=str)
    DeleteMovieFolderHelpText: str = attr.ib(type=str)
    DeleteMovieFolderLabel: str = attr.ib(type=str)
    DeleteNotification: str = attr.ib(type=str)
    DeleteNotificationMessageText: str = attr.ib(type=str)
    DeleteQualityProfile: str = attr.ib(type=str)
    DeleteQualityProfileMessageText: str = attr.ib(type=str)
    DeleteReleaseProfile: str = attr.ib(type=str)
    DeleteReleaseProfileMessageText: str = attr.ib(type=str)
    DeleteRestriction: str = attr.ib(type=str)
    DeleteRestrictionHelpText: str = attr.ib(type=str)
    DeleteRootFolder: str = attr.ib(type=str)
    DeleteRootFolderMessageText: str = attr.ib(type=str)
    DeleteSelectedBookFiles: str = attr.ib(type=str)
    DeleteSelectedBookFilesMessageText: str = attr.ib(type=str)
    DeleteSelectedMovie: str = attr.ib(type=str)
    DeleteSelectedMovieFiles: str = attr.ib(type=str)
    DeleteSelectedMovieFilesMessage: str = attr.ib(type=str)
    DeleteTag: str = attr.ib(type=str)
    DeleteTagMessageText: str = attr.ib(type=str)
    DeleteTheMovieFolder: str = attr.ib(type=str)
    DestinationPath: str = attr.ib(type=str)
    DestinationRelativePath: str = attr.ib(type=str)
    DetailedProgressBar: str = attr.ib(type=str)
    DetailedProgressBarHelpText: str = attr.ib(type=str)
    Details: str = attr.ib(type=str)
    Development: str = attr.ib(type=str)
    DigitalRelease: str = attr.ib(type=str)
    Disabled: str = attr.ib(type=str)
    DiscCount: str = attr.ib(type=str)
    DiscNumber: str = attr.ib(type=str)
    Discord: str = attr.ib(type=str)
    DiscordUrlInSlackNotification: str = attr.ib(type=str)
    Discover: str = attr.ib(type=str)
    DiskSpace: str = attr.ib(type=str)
    Docker: str = attr.ib(type=str)
    DockerUpdater: str = attr.ib(type=str)
    Donations: str = attr.ib(type=str)
    DoneEditingGroups: str = attr.ib(type=str)
    DoNotPrefer: str = attr.ib(type=str)
    DoNotUpgradeAutomatically: str = attr.ib(type=str)
    Download: str = attr.ib(type=str)
    DownloadClient: str = attr.ib(type=str)
    DownloadClientCheckDownloadingToRoot: str = attr.ib(type=str)
    DownloadClientCheckNoneAvailableMessage: str = attr.ib(type=str)
    DownloadClientCheckUnableToCommunicateMessage: str = attr.ib(type=str)
    DownloadClients: str = attr.ib(type=str)
    DownloadClientSettings: str = attr.ib(type=str)
    DownloadClientsSettingsSummary: str = attr.ib(type=str)
    DownloadClientStatusCheckAllClientMessage: str = attr.ib(type=str)
    DownloadClientStatusCheckSingleClientMessage: str = attr.ib(type=str)
    DownloadClientUnavailable: str = attr.ib(type=str)
    Downloaded: str = attr.ib(type=str)
    DownloadedAndMonitored: str = attr.ib(type=str)
    DownloadedButNotMonitored: str = attr.ib(type=str)
    DownloadFailed: str = attr.ib(type=str)
    DownloadFailedCheckDownloadClientForMoreDetails: str = attr.ib(type=str)
    DownloadFailedInterp: str = attr.ib(type=str)
    Downloading: str = attr.ib(type=str)
    DownloadPropersAndRepacks: str = attr.ib(type=str)
    DownloadPropersAndRepacksHelpText1: str = attr.ib(type=str)
    DownloadPropersAndRepacksHelpText2: str = attr.ib(type=str)
    DownloadPropersAndRepacksHelpTexts1: str = attr.ib(type=str)
    DownloadPropersAndRepacksHelpTexts2: str = attr.ib(type=str)
    DownloadPropersAndRepacksHelpTextWarning: str = attr.ib(type=str)
    DownloadWarning: str = attr.ib(type=str)
    DownloadWarningCheckDownloadClientForMoreDetails: str = attr.ib(type=str)
    Edit: str = attr.ib(type=str)
    EditAuthor: str = attr.ib(type=str)
    EditCustomFormat: str = attr.ib(type=str)
    EditDelayProfile: str = attr.ib(type=str)
    EditGroups: str = attr.ib(type=str)
    EditIndexer: str = attr.ib(type=str)
    Edition: str = attr.ib(type=str)
    EditionsHelpText: str = attr.ib(type=str)
    EditListExclusion: str = attr.ib(type=str)
    EditMovie: str = attr.ib(type=str)
    EditMovieFile: str = attr.ib(type=str)
    EditPerson: str = attr.ib(type=str)
    EditQualityProfile: str = attr.ib(type=str)
    EditRemotePathMapping: str = attr.ib(type=str)
    EditRestriction: str = attr.ib(type=str)
    EmbedMetadataHelpText: str = attr.ib(type=str)
    EmbedMetadataInBookFiles: str = attr.ib(type=str)
    Enable: str = attr.ib(type=str)
    EnableAutoHelpText: str = attr.ib(type=str)
    EnableAutomaticAdd: str = attr.ib(type=str)
    EnableAutomaticAddHelpText: str = attr.ib(type=str)
    EnableAutomaticSearch: str = attr.ib(type=str)
    EnableAutomaticSearchHelpText: str = attr.ib(type=str)
    EnableAutomaticSearchHelpTextWarning: str = attr.ib(type=str)
    EnableColorImpairedMode: str = attr.ib(type=str)
    EnableColorImpairedModeHelpText: str = attr.ib(type=str)
    EnableCompletedDownloadHandlingHelpText: str = attr.ib(type=str)
    Enabled: str = attr.ib(type=str)
    EnabledHelpText: str = attr.ib(type=str)
    EnableHelpText: str = attr.ib(type=str)
    EnableInteractiveSearch: str = attr.ib(type=str)
    EnableInteractiveSearchHelpText: str = attr.ib(type=str)
    EnableInteractiveSearchHelpTextWarning: str = attr.ib(type=str)
    EnableMediaInfoHelpText: str = attr.ib(type=str)
    EnableProfile: str = attr.ib(type=str)
    EnableRSS: str = attr.ib(type=str)
    EnableSSL: str = attr.ib(type=str)
    EnableSslHelpText: str = attr.ib(type=str)
    Ended: str = attr.ib(type=str)
    EndedAllBooksDownloaded: str = attr.ib(type=str)
    EntityName: str = attr.ib(type=str)
    Episode: str = attr.ib(type=str)
    EpisodeDoesNotHaveAnAbsoluteEpisodeNumber: str = attr.ib(type=str)
    Error: str = attr.ib(type=str)
    ErrorLoadingContents: str = attr.ib(type=str)
    ErrorLoadingPreviews: str = attr.ib(type=str)
    ErrorRestoringBackup: str = attr.ib(type=str)
    Events: str = attr.ib(type=str)
    EventType: str = attr.ib(type=str)
    Exception: str = attr.ib(type=str)
    Excluded: str = attr.ib(type=str)
    ExcludeMovie: str = attr.ib(type=str)
    ExcludeTitle: str = attr.ib(type=str)
    Existing: str = attr.ib(type=str)
    ExistingBooks: str = attr.ib(type=str)
    ExistingItems: str = attr.ib(type=str)
    ExistingMovies: str = attr.ib(type=str)
    ExistingTag: str = attr.ib(type=str)
    ExistingTagsScrubbed: str = attr.ib(type=str)
    ExportCustomFormat: str = attr.ib(type=str)
    Extension: str = attr.ib(type=str)
    ExternalUpdater: str = attr.ib(type=str)
    ExtraFileExtensionsHelpTexts1: str = attr.ib(type=str)
    ExtraFileExtensionsHelpTexts2: str = attr.ib(type=str)
    Failed: str = attr.ib(type=str)
    FailedDownloadHandling: str = attr.ib(type=str)
    FailedLoadingSearchResults: str = attr.ib(type=str)
    FailedToLoadMovieFromAPI: str = attr.ib(type=str)
    FailedToLoadQueue: str = attr.ib(type=str)
    FeatureRequests: str = attr.ib(type=str)
    FileDateHelpText: str = attr.ib(type=str)
    FileDetails: str = attr.ib(type=str)
    FileManagement: str = attr.ib(type=str)
    Filename: str = attr.ib(type=str)
    FileNames: str = attr.ib(type=str)
    FileNameTokens: str = attr.ib(type=str)
    Files: str = attr.ib(type=str)
    FilesTotal: str = attr.ib(type=str)
    FileWasDeletedByUpgrade: str = attr.ib(type=str)
    FileWasDeletedByViaUI: str = attr.ib(type=str)
    Filter: str = attr.ib(type=str)
    FilterAnalyticsEvents: str = attr.ib(type=str)
    FilterAuthor: str = attr.ib(type=str)
    FilterPlaceHolder: str = attr.ib(type=str)
    Filters: str = attr.ib(type=str)
    FilterSentryEventsHelpText: str = attr.ib(type=str)
    FirstBook: str = attr.ib(type=str)
    FirstDayOfWeek: str = attr.ib(type=str)
    Fixed: str = attr.ib(type=str)
    FocusSearchBox: str = attr.ib(type=str)
    Folder: str = attr.ib(type=str)
    FolderMoveRenameWarning: str = attr.ib(type=str)
    Folders: str = attr.ib(type=str)
    FollowPerson: str = attr.ib(type=str)
    Forecast: str = attr.ib(type=str)
    ForeignIdHelpText: str = attr.ib(type=str)
    Formats: str = attr.ib(type=str)
    ForMoreInformationOnTheIndividualDownloadClients: str = attr.ib(type=str)
    ForMoreInformationOnTheIndividualDownloadClientsClickOnTheInfoButtons: str = (
        attr.ib(type=str)
    )
    ForMoreInformationOnTheIndividualImportListsClinkOnTheInfoButtons: str = attr.ib(
        type=str
    )
    ForMoreInformationOnTheIndividualIndexers: str = attr.ib(type=str)
    ForMoreInformationOnTheIndividualIndexersClickOnTheInfoButtons: str = attr.ib(
        type=str
    )
    ForMoreInformationOnTheIndividualListsClickOnTheInfoButtons: str = attr.ib(type=str)
    FreeSpace: str = attr.ib(type=str)
    From: str = attr.ib(type=str)
    FutureBooks: str = attr.ib(type=str)
    FutureDays: str = attr.ib(type=str)
    FutureDaysHelpText: str = attr.ib(type=str)
    General: str = attr.ib(type=str)
    GeneralSettings: str = attr.ib(type=str)
    GeneralSettingsSummary: str = attr.ib(type=str)
    Genres: str = attr.ib(type=str)
    Global: str = attr.ib(type=str)
    GoToAuthorListing: str = attr.ib(type=str)
    GoToInterp: str = attr.ib(type=str)
    Grab: str = attr.ib(type=str)
    Grabbed: str = attr.ib(type=str)
    GrabID: str = attr.ib(type=str)
    GrabRelease: str = attr.ib(type=str)
    GrabReleaseMessageText: str = attr.ib(type=str)
    GrabSelected: str = attr.ib(type=str)
    Group: str = attr.ib(type=str)
    HardlinkCopyFiles: str = attr.ib(type=str)
    HasMonitoredBooksNoMonitoredBooksForThisAuthor: str = attr.ib(type=str)
    HasPendingChangesNoChanges: str = attr.ib(type=str)
    HasPendingChangesSaveChanges: str = attr.ib(type=str)
    HaveNotAddedMovies: str = attr.ib(type=str)
    Health: str = attr.ib(type=str)
    HealthNoIssues: str = attr.ib(type=str)
    HelpText: str = attr.ib(type=str)
    HiddenClickToShow: str = attr.ib(type=str)
    HideAdvanced: str = attr.ib(type=str)
    HideBooks: str = attr.ib(type=str)
    History: str = attr.ib(type=str)
    HomePage: str = attr.ib(type=str)
    Host: str = attr.ib(type=str)
    HostHelpText: str = attr.ib(type=str)
    Hostname: str = attr.ib(type=str)
    Hours: str = attr.ib(type=str)
    HttpHttps: str = attr.ib(type=str)
    ICalFeed: str = attr.ib(type=str)
    ICalHttpUrlHelpText: str = attr.ib(type=str)
    iCalLink: str = attr.ib(type=str)
    ICalLink: str = attr.ib(type=str)
    IconForCutoffUnmet: str = attr.ib(type=str)
    IconTooltip: str = attr.ib(type=str)
    IfYouDontAddAnImportListExclusionAndTheAuthorHasAMetadataProfileOtherThanNoneThenThisBookMayBeReaddedDuringTheNextAuthorRefresh: str | None = (
        None
    )
    Ignored: str = attr.ib(type=str)
    IgnoredAddresses: str = attr.ib(type=str)
    IgnoreDeletedBooks: str = attr.ib(type=str)
    IgnoreDeletedMovies: str = attr.ib(type=str)
    IgnoredHelpText: str = attr.ib(type=str)
    IgnoredMetaHelpText: str = attr.ib(type=str)
    IgnoredPlaceHolder: str = attr.ib(type=str)
    IllRestartLater: str = attr.ib(type=str)
    Images: str = attr.ib(type=str)
    IMDb: str = attr.ib(type=str)
    ImdbRating: str = attr.ib(type=str)
    ImdbVotes: str = attr.ib(type=str)
    Import: str = attr.ib(type=str)
    ImportCustomFormat: str = attr.ib(type=str)
    Imported: str = attr.ib(type=str)
    ImportedTo: str = attr.ib(type=str)
    ImportErrors: str = attr.ib(type=str)
    ImportExistingMovies: str = attr.ib(type=str)
    ImportExtraFiles: str = attr.ib(type=str)
    ImportExtraFilesHelpText: str = attr.ib(type=str)
    ImportFailed: str = attr.ib(type=str)
    ImportFailedInterp: str = attr.ib(type=str)
    ImportFailures: str = attr.ib(type=str)
    ImportHeader: str = attr.ib(type=str)
    ImportIncludeQuality: str = attr.ib(type=str)
    Importing: str = attr.ib(type=str)
    ImportLibrary: str = attr.ib(type=str)
    ImportListExclusions: str = attr.ib(type=str)
    ImportListMissingRoot: str = attr.ib(type=str)
    ImportListMultipleMissingRoots: str = attr.ib(type=str)
    ImportLists: str = attr.ib(type=str)
    ImportListSettings: str = attr.ib(type=str)
    ImportListSpecificSettings: str = attr.ib(type=str)
    ImportListStatusCheckAllClientMessage: str = attr.ib(type=str)
    ImportListStatusCheckSingleClientMessage: str = attr.ib(type=str)
    ImportListSyncIntervalHelpText: str = attr.ib(type=str)
    ImportMechanismHealthCheckMessage: str = attr.ib(type=str)
    ImportMovies: str = attr.ib(type=str)
    ImportNotForDownloads: str = attr.ib(type=str)
    ImportRootPath: str = attr.ib(type=str)
    ImportTipsMessage: str = attr.ib(type=str)
    InCinemas: str = attr.ib(type=str)
    InCinemasDate: str = attr.ib(type=str)
    InCinemasMsg: str = attr.ib(type=str)
    IncludeCustomFormatWhenRenaming: str = attr.ib(type=str)
    IncludeCustomFormatWhenRenamingHelpText: str = attr.ib(type=str)
    IncludeHealthWarningsHelpText: str = attr.ib(type=str)
    IncludePreferredWhenRenaming: str = attr.ib(type=str)
    IncludeRadarrRecommendations: str = attr.ib(type=str)
    IncludeRecommendationsHelpText: str = attr.ib(type=str)
    IncludeUnknownAuthorItemsHelpText: str = attr.ib(type=str)
    IncludeUnknownMovieItemsHelpText: str = attr.ib(type=str)
    IncludeUnmonitored: str = attr.ib(type=str)
    Indexer: str = attr.ib(type=str)
    IndexerDownloadClientHelpText: str = attr.ib(type=str)
    IndexerFlags: str = attr.ib(type=str)
    IndexerIdHelpText: str = attr.ib(type=str)
    IndexerIdHelpTextWarning: str = attr.ib(type=str)
    IndexerIdvalue0IncludeInPreferredWordsRenamingFormat: str = attr.ib(type=str)
    IndexerIdvalue0OnlySupportedWhenIndexerIsSetToAll: str = attr.ib(type=str)
    IndexerJackettAll: str = attr.ib(type=str)
    IndexerLongTermStatusCheckAllClientMessage: str = attr.ib(type=str)
    IndexerLongTermStatusCheckSingleClientMessage: str = attr.ib(type=str)
    IndexerPriority: str = attr.ib(type=str)
    IndexerPriorityHelpText: str = attr.ib(type=str)
    IndexerRssHealthCheckNoAvailableIndexers: str = attr.ib(type=str)
    IndexerRssHealthCheckNoIndexers: str = attr.ib(type=str)
    Indexers: str = attr.ib(type=str)
    IndexerSearchCheckNoAutomaticMessage: str = attr.ib(type=str)
    IndexerSearchCheckNoAvailableIndexersMessage: str = attr.ib(type=str)
    IndexerSearchCheckNoInteractiveMessage: str = attr.ib(type=str)
    IndexerSettings: str = attr.ib(type=str)
    IndexersSettingsSummary: str = attr.ib(type=str)
    IndexerStatusCheckAllClientMessage: str = attr.ib(type=str)
    IndexerStatusCheckSingleClientMessage: str = attr.ib(type=str)
    IndexerTagHelpText: str = attr.ib(type=str)
    Info: str = attr.ib(type=str)
    InstallLatest: str = attr.ib(type=str)
    InteractiveImport: str = attr.ib(type=str)
    InteractiveImportErrLanguage: str = attr.ib(type=str)
    InteractiveImportErrMovie: str = attr.ib(type=str)
    InteractiveImportErrQuality: str = attr.ib(type=str)
    InteractiveSearch: str = attr.ib(type=str)
    Interval: str = attr.ib(type=str)
    InvalidFormat: str = attr.ib(type=str)
    ISBN: str = attr.ib(type=str)
    IsCalibreLibraryHelpText: str = attr.ib(type=str)
    IsCutoffCutoff: str = attr.ib(type=str)
    IsCutoffUpgradeUntilThisQualityIsMetOrExceeded: str = attr.ib(type=str)
    IsExpandedHideBooks: str = attr.ib(type=str)
    IsExpandedHideFileInfo: str = attr.ib(type=str)
    IsExpandedShowBooks: str = attr.ib(type=str)
    IsExpandedShowFileInfo: str = attr.ib(type=str)
    IsInUseCantDeleteAMetadataProfileThatIsAttachedToAnAuthorOrImportList: str | None = (
        None
    )
    IsInUseCantDeleteAQualityProfileThatIsAttachedToAnAuthorOrImportList: str | None = (
        None
    )
    IsShowingMonitoredMonitorSelected: str = attr.ib(type=str)
    IsShowingMonitoredUnmonitorSelected: str = attr.ib(type=str)
    IsTagUsedCannotBeDeletedWhileInUse: str = attr.ib(type=str)
    KeepAndUnmonitorMovie: str = attr.ib(type=str)
    KeyboardShortcuts: str = attr.ib(type=str)
    Label: str = attr.ib(type=str)
    Language: str = attr.ib(type=str)
    LanguageHelpText: str = attr.ib(type=str)
    Languages: str = attr.ib(type=str)
    Large: str = attr.ib(type=str)
    LastDuration: str = attr.ib(type=str)
    LastExecution: str = attr.ib(type=str)
    LastUsed: str = attr.ib(type=str)
    LastWriteTime: str = attr.ib(type=str)
    LatestBook: str = attr.ib(type=str)
    LaunchBrowserHelpText: str = attr.ib(type=str)
    Letterboxd: str = attr.ib(type=str)
    Level: str = attr.ib(type=str)
    LibraryHelpText: str = attr.ib(type=str)
    LinkHere: str = attr.ib(type=str)
    Links: str = attr.ib(type=str)
    ListExclusions: str = attr.ib(type=str)
    Lists: str = attr.ib(type=str)
    ListSettings: str = attr.ib(type=str)
    ListsSettingsSummary: str = attr.ib(type=str)
    ListSyncLevelHelpText: str = attr.ib(type=str)
    ListSyncLevelHelpTextWarning: str = attr.ib(type=str)
    ListTagsHelpText: str = attr.ib(type=str)
    ListUpdateInterval: str = attr.ib(type=str)
    LoadingBookFilesFailed: str = attr.ib(type=str)
    LoadingBooksFailed: str = attr.ib(type=str)
    LoadingMovieCreditsFailed: str = attr.ib(type=str)
    LoadingMovieExtraFilesFailed: str = attr.ib(type=str)
    LoadingMovieFilesFailed: str = attr.ib(type=str)
    Local: str = attr.ib(type=str)
    LocalPath: str = attr.ib(type=str)
    LocalPathHelpText: str = attr.ib(type=str)
    Location: str = attr.ib(type=str)
    LogFiles: str = attr.ib(type=str)
    Logging: str = attr.ib(type=str)
    LogLevel: str = attr.ib(type=str)
    LogLevelTraceHelpTextWarning: str = attr.ib(type=str)
    LogLevelvalueTraceTraceLoggingShouldOnlyBeEnabledTemporarily: str = attr.ib(
        type=str
    )
    LogOnly: str = attr.ib(type=str)
    LogRotateHelpText: str = attr.ib(type=str)
    LogRotation: str = attr.ib(type=str)
    Logs: str = attr.ib(type=str)
    LogSQL: str = attr.ib(type=str)
    LogSqlHelpText: str = attr.ib(type=str)
    LongDateFormat: str = attr.ib(type=str)
    LookingForReleaseProfiles1: str = attr.ib(type=str)
    LookingForReleaseProfiles2: str = attr.ib(type=str)
    LowerCase: str = attr.ib(type=str)
    MaintenanceRelease: str = attr.ib(type=str)
    Manual: str = attr.ib(type=str)
    ManualDownload: str = attr.ib(type=str)
    ManualImport: str = attr.ib(type=str)
    ManualImportSelectLanguage: str = attr.ib(type=str)
    ManualImportSelectMovie: str = attr.ib(type=str)
    ManualImportSelectQuality: str = attr.ib(type=str)
    ManualImportSetReleaseGroup: str = attr.ib(type=str)
    MappedDrivesRunningAsService: str = attr.ib(type=str)
    MarkAsFailed: str = attr.ib(type=str)
    MarkAsFailedMessageText: str = attr.ib(type=str)
    MassBookSearch: str = attr.ib(type=str)
    MassBookSearchWarning: str = attr.ib(type=str)
    MassMovieSearch: str = attr.ib(type=str)
    Max: str = attr.ib(type=str)
    MaximumLimits: str = attr.ib(type=str)
    MaximumSize: str = attr.ib(type=str)
    MaximumSizeHelpText: str = attr.ib(type=str)
    Mechanism: str = attr.ib(type=str)
    MediaInfo: str = attr.ib(type=str)
    MediaManagement: str = attr.ib(type=str)
    MediaManagementSettings: str = attr.ib(type=str)
    MediaManagementSettingsSummary: str = attr.ib(type=str)
    Medium: str = attr.ib(type=str)
    MediumFormat: str = attr.ib(type=str)
    MegabytesPerMinute: str = attr.ib(type=str)
    Message: str = attr.ib(type=str)
    Metadata: str = attr.ib(type=str)
    MetadataConsumers: str = attr.ib(type=str)
    MetadataProfile: str = attr.ib(type=str)
    MetadataProfileIdHelpText: str = attr.ib(type=str)
    MetadataProfiles: str = attr.ib(type=str)
    MetadataProviderSource: str = attr.ib(type=str)
    MetadataSettings: str = attr.ib(type=str)
    MetadataSettingsSummary: str = attr.ib(type=str)
    MetadataSource: str = attr.ib(type=str)
    MetadataSourceHelpText: str = attr.ib(type=str)
    MIA: str = attr.ib(type=str)
    Min: str = attr.ib(type=str)
    MinAvailability: str = attr.ib(type=str)
    MinFormatScoreHelpText: str = attr.ib(type=str)
    MinimumAge: str = attr.ib(type=str)
    MinimumAgeHelpText: str = attr.ib(type=str)
    MinimumAvailability: str = attr.ib(type=str)
    MinimumCustomFormatScore: str = attr.ib(type=str)
    MinimumFreeSpace: str = attr.ib(type=str)
    MinimumFreeSpaceWhenImportingHelpText: str = attr.ib(type=str)
    MinimumLimits: str = attr.ib(type=str)
    MinimumPages: str = attr.ib(type=str)
    MinimumPopularity: str = attr.ib(type=str)
    MinPagesHelpText: str = attr.ib(type=str)
    MinPopularityHelpText: str = attr.ib(type=str)
    Minutes: str = attr.ib(type=str)
    MinutesHundredTwenty: str = attr.ib(type=str)
    MinutesNinety: str = attr.ib(type=str)
    MinutesSixty: str = attr.ib(type=str)
    Missing: str = attr.ib(type=str)
    MissingBooks: str = attr.ib(type=str)
    MissingBooksAuthorMonitored: str = attr.ib(type=str)
    MissingBooksAuthorNotMonitored: str = attr.ib(type=str)
    MissingFromDisk: str = attr.ib(type=str)
    MissingMonitoredAndConsideredAvailable: str = attr.ib(type=str)
    MissingNotMonitored: str = attr.ib(type=str)
    Mode: str = attr.ib(type=str)
    Monday: str = attr.ib(type=str)
    Monitor: str = attr.ib(type=str)
    MonitorAuthor: str = attr.ib(type=str)
    MonitorBook: str = attr.ib(type=str)
    MonitorBookExistingOnlyWarning: str = attr.ib(type=str)
    Monitored: str = attr.ib(type=str)
    MonitoredAuthorIsMonitored: str = attr.ib(type=str)
    MonitoredAuthorIsUnmonitored: str = attr.ib(type=str)
    MonitoredHelpText: str = attr.ib(type=str)
    MonitoredOnly: str = attr.ib(type=str)
    MonitoredStatus: str = attr.ib(type=str)
    Monitoring: str = attr.ib(type=str)
    MonitoringOptions: str = attr.ib(type=str)
    MonitoringOptionsHelpText: str = attr.ib(type=str)
    MonitorMovie: str = attr.ib(type=str)
    MonitorNewItems: str = attr.ib(type=str)
    MonitorNewItemsHelpText: str = attr.ib(type=str)
    MonoVersion: str = attr.ib(type=str)
    Month: str = attr.ib(type=str)
    Months: str = attr.ib(type=str)
    More: str = attr.ib(type=str)
    MoreControlCFText: str = attr.ib(type=str)
    MoreDetails: str = attr.ib(type=str)
    MoreInfo: str = attr.ib(type=str)
    MountCheckMessage: str = attr.ib(type=str)
    MoveFiles: str = attr.ib(type=str)
    MoveFolders1: str = attr.ib(type=str)
    MoveFolders2: str = attr.ib(type=str)
    Movie: str = attr.ib(type=str)
    MovieAlreadyExcluded: str = attr.ib(type=str)
    MovieChat: str = attr.ib(type=str)
    MovieDetailsNextMovie: str = attr.ib(type=str)
    MovieDetailsPreviousMovie: str = attr.ib(type=str)
    MovieEditor: str = attr.ib(type=str)
    MovieExcludedFromAutomaticAdd: str = attr.ib(type=str)
    MovieFiles: str = attr.ib(type=str)
    MovieFilesTotaling: str = attr.ib(type=str)
    MovieFolderFormat: str = attr.ib(type=str)
    MovieID: str = attr.ib(type=str)
    MovieIndex: str = attr.ib(type=str)
    MovieIndexScrollBottom: str = attr.ib(type=str)
    MovieIndexScrollTop: str = attr.ib(type=str)
    MovieInfoLanguage: str = attr.ib(type=str)
    MovieInfoLanguageHelpText: str = attr.ib(type=str)
    MovieInfoLanguageHelpTextWarning: str = attr.ib(type=str)
    MovieInvalidFormat: str = attr.ib(type=str)
    MovieIsDownloading: str = attr.ib(type=str)
    MovieIsDownloadingInterp: str = attr.ib(type=str)
    MovieIsMonitored: str = attr.ib(type=str)
    MovieIsOnImportExclusionList: str = attr.ib(type=str)
    MovieIsRecommend: str = attr.ib(type=str)
    MovieIsUnmonitored: str = attr.ib(type=str)
    MovieNaming: str = attr.ib(type=str)
    Movies: str = attr.ib(type=str)
    MoviesSelectedInterp: str = attr.ib(type=str)
    MovieTitle: str = attr.ib(type=str)
    MovieTitleHelpText: str = attr.ib(type=str)
    MovieYear: str = attr.ib(type=str)
    MovieYearHelpText: str = attr.ib(type=str)
    MultiLanguage: str = attr.ib(type=str)
    MusicBrainzAuthorID: str = attr.ib(type=str)
    MusicBrainzBookID: str = attr.ib(type=str)
    MusicbrainzId: str = attr.ib(type=str)
    MusicBrainzRecordingID: str = attr.ib(type=str)
    MusicBrainzReleaseID: str = attr.ib(type=str)
    MusicBrainzTrackID: str = attr.ib(type=str)
    MustContain: str = attr.ib(type=str)
    MustNotContain: str = attr.ib(type=str)
    Name: str = attr.ib(type=str)
    NameFirstLast: str = attr.ib(type=str)
    NameLastFirst: str = attr.ib(type=str)
    NameStyle: str = attr.ib(type=str)
    NamingSettings: str = attr.ib(type=str)
    Negate: str = attr.ib(type=str)
    Negated: str = attr.ib(type=str)
    NegateHelpText: str = attr.ib(type=str)
    NetCore: str = attr.ib(type=str)
    NETCore: str = attr.ib(type=str)
    New: str = attr.ib(type=str)
    NewBooks: str = attr.ib(type=str)
    NextExecution: str = attr.ib(type=str)
    No: str = attr.ib(type=str)
    NoAltTitle: str = attr.ib(type=str)
    NoBackupsAreAvailable: str = attr.ib(type=str)
    NoChange: str = attr.ib(type=str)
    NoChanges: str = attr.ib(type=str)
    NoEventsFound: str = attr.ib(type=str)
    NoHistory: str = attr.ib(type=str)
    NoHistoryBlocklist: str = attr.ib(type=str)
    NoLeaveIt: str = attr.ib(type=str)
    NoLimitForAnyRuntime: str = attr.ib(type=str)
    NoLinks: str = attr.ib(type=str)
    NoListRecommendations: str = attr.ib(type=str)
    NoLogFiles: str = attr.ib(type=str)
    NoMatchFound: str = attr.ib(type=str)
    NoMinimumForAnyRuntime: str = attr.ib(type=str)
    NoMoveFilesSelf: str = attr.ib(type=str)
    NoMoviesExist: str = attr.ib(type=str)
    NoName: str = attr.ib(type=str)
    NoResultsFound: str = attr.ib(type=str)
    NoTagsHaveBeenAddedYet: str = attr.ib(type=str)
    NotAvailable: str = attr.ib(type=str)
    NotificationTriggers: str = attr.ib(type=str)
    NotificationTriggersHelpText: str = attr.ib(type=str)
    NotMonitored: str = attr.ib(type=str)
    NoUpdatesAreAvailable: str = attr.ib(type=str)
    NoVideoFilesFoundSelectedFolder: str = attr.ib(type=str)
    OAuthPopupMessage: str = attr.ib(type=str)
    Ok: str = attr.ib(type=str)
    OnApplicationUpdate: str = attr.ib(type=str)
    OnApplicationUpdateHelpText: str = attr.ib(type=str)
    OnBookRetagHelpText: str = attr.ib(type=str)
    OnDownloadFailureHelpText: str = attr.ib(type=str)
    OnDownloadHelpText: str = attr.ib(type=str)
    OnGrab: str = attr.ib(type=str)
    OnGrabHelpText: str = attr.ib(type=str)
    OnHealthIssue: str = attr.ib(type=str)
    OnHealthIssueHelpText: str = attr.ib(type=str)
    OnImport: str = attr.ib(type=str)
    OnImportFailureHelpText: str = attr.ib(type=str)
    OnLatestVersion: str = attr.ib(type=str)
    OnlyTorrent: str = attr.ib(type=str)
    OnlyUsenet: str = attr.ib(type=str)
    OnMovieDelete: str = attr.ib(type=str)
    OnMovieDeleteHelpText: str = attr.ib(type=str)
    OnMovieFileDelete: str = attr.ib(type=str)
    OnMovieFileDeleteForUpgrade: str = attr.ib(type=str)
    OnMovieFileDeleteForUpgradeHelpText: str = attr.ib(type=str)
    OnMovieFileDeleteHelpText: str = attr.ib(type=str)
    OnReleaseImportHelpText: str = attr.ib(type=str)
    OnRename: str = attr.ib(type=str)
    OnRenameHelpText: str = attr.ib(type=str)
    OnUpgrade: str = attr.ib(type=str)
    OnUpgradeHelpText: str = attr.ib(type=str)
    OpenBrowserOnStart: str = attr.ib(type=str)
    OpenThisModal: str = attr.ib(type=str)
    Options: str = attr.ib(type=str)
    Organize: str = attr.ib(type=str)
    OrganizeAndRename: str = attr.ib(type=str)
    OrganizeConfirm: str = attr.ib(type=str)
    OrganizeModalAllPathsRelative: str = attr.ib(type=str)
    OrganizeModalDisabled: str = attr.ib(type=str)
    OrganizeModalNamingPattern: str = attr.ib(type=str)
    OrganizeModalSuccess: str = attr.ib(type=str)
    OrganizeSelectedMovies: str = attr.ib(type=str)
    Original: str = attr.ib(type=str)
    Other: str = attr.ib(type=str)
    OutputFormatHelpText: str = attr.ib(type=str)
    OutputPath: str = attr.ib(type=str)
    Overview: str = attr.ib(type=str)
    OverviewOptions: str = attr.ib(type=str)
    PackageVersion: str = attr.ib(type=str)
    PageSize: str = attr.ib(type=str)
    PageSizeHelpText: str = attr.ib(type=str)
    Password: str = attr.ib(type=str)
    PasswordHelpText: str = attr.ib(type=str)
    PastDays: str = attr.ib(type=str)
    PastDaysHelpText: str = attr.ib(type=str)
    Path: str = attr.ib(type=str)
    PathHelpText: str = attr.ib(type=str)
    PathHelpTextWarning: str = attr.ib(type=str)
    Paused: str = attr.ib(type=str)
    Peers: str = attr.ib(type=str)
    Pending: str = attr.ib(type=str)
    PendingChangesDiscardChanges: str = attr.ib(type=str)
    PendingChangesMessage: str = attr.ib(type=str)
    PendingChangesStayReview: str = attr.ib(type=str)
    Permissions: str = attr.ib(type=str)
    PhysicalRelease: str = attr.ib(type=str)
    PhysicalReleaseDate: str = attr.ib(type=str)
    Port: str = attr.ib(type=str)
    PortHelpText: str = attr.ib(type=str)
    PortHelpTextWarning: str = attr.ib(type=str)
    PortNumber: str = attr.ib(type=str)
    PosterOptions: str = attr.ib(type=str)
    Posters: str = attr.ib(type=str)
    PosterSize: str = attr.ib(type=str)
    PreferAndUpgrade: str = attr.ib(type=str)
    PreferIndexerFlags: str = attr.ib(type=str)
    PreferIndexerFlagsHelpText: str = attr.ib(type=str)
    Preferred: str = attr.ib(type=str)
    PreferredHelpTexts1: str = attr.ib(type=str)
    PreferredHelpTexts2: str = attr.ib(type=str)
    PreferredHelpTexts3: str = attr.ib(type=str)
    PreferredSize: str = attr.ib(type=str)
    PreferTorrent: str = attr.ib(type=str)
    PreferUsenet: str = attr.ib(type=str)
    Presets: str = attr.ib(type=str)
    PreviewRename: str = attr.ib(type=str)
    PreviewRenameHelpText: str = attr.ib(type=str)
    PreviewRetag: str = attr.ib(type=str)
    Priority: str = attr.ib(type=str)
    PriorityHelpText: str = attr.ib(type=str)
    PrioritySettings: str = attr.ib(type=str)
    ProcessingFolders: str = attr.ib(type=str)
    Profiles: str = attr.ib(type=str)
    ProfilesSettingsSummary: str = attr.ib(type=str)
    Progress: str = attr.ib(type=str)
    Proper: str = attr.ib(type=str)
    PropersAndRepacks: str = attr.ib(type=str)
    Protocol: str = attr.ib(type=str)
    ProtocolHelpText: str = attr.ib(type=str)
    Proxy: str = attr.ib(type=str)
    ProxyBypassFilterHelpText: str = attr.ib(type=str)
    ProxyCheckBadRequestMessage: str = attr.ib(type=str)
    ProxyCheckFailedToTestMessage: str = attr.ib(type=str)
    ProxyCheckResolveIpMessage: str = attr.ib(type=str)
    ProxyPasswordHelpText: str = attr.ib(type=str)
    ProxyType: str = attr.ib(type=str)
    ProxyUsernameHelpText: str = attr.ib(type=str)
    PtpOldSettingsCheckMessage: str = attr.ib(type=str)
    PublishedDate: str = attr.ib(type=str)
    Publisher: str = attr.ib(type=str)
    Qualities: str = attr.ib(type=str)
    QualitiesHelpText: str = attr.ib(type=str)
    Quality: str = attr.ib(type=str)
    QualityCutoffHasNotBeenMet: str = attr.ib(type=str)
    QualityDefinitions: str = attr.ib(type=str)
    QualityLimitsHelpText: str = attr.ib(type=str)
    QualityOrLangCutoffHasNotBeenMet: str = attr.ib(type=str)
    QualityProfile: str = attr.ib(type=str)
    QualityProfileDeleteConfirm: str = attr.ib(type=str)
    QualityProfileIdHelpText: str = attr.ib(type=str)
    QualityProfileInUse: str = attr.ib(type=str)
    QualityProfiles: str = attr.ib(type=str)
    QualitySettings: str = attr.ib(type=str)
    QualitySettingsSummary: str = attr.ib(type=str)
    Queue: str = attr.ib(type=str)
    Queued: str = attr.ib(type=str)
    QueueIsEmpty: str = attr.ib(type=str)
    QuickImport: str = attr.ib(type=str)
    RadarrCalendarFeed: str = attr.ib(type=str)
    RadarrSupportsAnyDownloadClient: str = attr.ib(type=str)
    RadarrSupportsAnyIndexer: str = attr.ib(type=str)
    RadarrSupportsAnyRSSMovieListsAsWellAsTheOneStatedBelow: str = attr.ib(type=str)
    RadarrSupportsCustomConditionsAgainstTheReleasePropertiesBelow: str = attr.ib(
        type=str
    )
    RadarrTags: str = attr.ib(type=str)
    RadarrUpdated: str = attr.ib(type=str)
    Ratings: str = attr.ib(type=str)
    ReadarrSupportsAnyDownloadClientThatUsesTheNewznabStandardAsWellAsOtherDownloadClientsListedBelow: str | None = (
        None
    )
    ReadarrSupportsAnyIndexerThatUsesTheNewznabStandardAsWellAsOtherIndexersListedBelow: str | None = (
        None
    )
    ReadarrSupportsMultipleListsForImportingBooksAndAuthorsIntoTheDatabase: str | None = (
        None
    )
    ReadarrTags: str = attr.ib(type=str)
    ReadTheWikiForMoreInformation: str = attr.ib(type=str)
    Real: str = attr.ib(type=str)
    Reason: str = attr.ib(type=str)
    RecentChanges: str = attr.ib(type=str)
    RecentFolders: str = attr.ib(type=str)
    RecycleBinCleanupDaysHelpText: str = attr.ib(type=str)
    RecycleBinCleanupDaysHelpTextWarning: str = attr.ib(type=str)
    RecycleBinHelpText: str = attr.ib(type=str)
    RecyclingBin: str = attr.ib(type=str)
    RecyclingBinCleanup: str = attr.ib(type=str)
    Reddit: str = attr.ib(type=str)
    Redownload: str = attr.ib(type=str)
    Refresh: str = attr.ib(type=str)
    RefreshAndScan: str = attr.ib(type=str)
    RefreshAuthor: str = attr.ib(type=str)
    RefreshInformation: str = attr.ib(type=str)
    RefreshInformationAndScanDisk: str = attr.ib(type=str)
    RefreshLists: str = attr.ib(type=str)
    RefreshMovie: str = attr.ib(type=str)
    RefreshScan: str = attr.ib(type=str)
    RegularExpressionsCanBeTested: str = attr.ib(type=str)
    RejectionCount: str = attr.ib(type=str)
    RelativePath: str = attr.ib(type=str)
    ReleaseBranchCheckOfficialBranchMessage: str = attr.ib(type=str)
    Released: str = attr.ib(type=str)
    ReleaseDate: str = attr.ib(type=str)
    ReleaseDates: str = attr.ib(type=str)
    ReleasedMsg: str = attr.ib(type=str)
    ReleaseGroup: str = attr.ib(type=str)
    ReleaseProfiles: str = attr.ib(type=str)
    ReleaseRejected: str = attr.ib(type=str)
    ReleaseStatus: str = attr.ib(type=str)
    ReleaseTitle: str = attr.ib(type=str)
    ReleaseWillBeProcessedInterp: str = attr.ib(type=str)
    Reload: str = attr.ib(type=str)
    RemotePath: str = attr.ib(type=str)
    RemotePathHelpText: str = attr.ib(type=str)
    RemotePathMappingCheckBadDockerPath: str = attr.ib(type=str)
    RemotePathMappingCheckDockerFolderMissing: str = attr.ib(type=str)
    RemotePathMappingCheckDownloadPermissions: str = attr.ib(type=str)
    RemotePathMappingCheckFileRemoved: str = attr.ib(type=str)
    RemotePathMappingCheckFilesBadDockerPath: str = attr.ib(type=str)
    RemotePathMappingCheckFilesGenericPermissions: str = attr.ib(type=str)
    RemotePathMappingCheckFilesLocalWrongOSPath: str = attr.ib(type=str)
    RemotePathMappingCheckFilesWrongOSPath: str = attr.ib(type=str)
    RemotePathMappingCheckFolderPermissions: str = attr.ib(type=str)
    RemotePathMappingCheckGenericPermissions: str = attr.ib(type=str)
    RemotePathMappingCheckImportFailed: str = attr.ib(type=str)
    RemotePathMappingCheckLocalFolderMissing: str = attr.ib(type=str)
    RemotePathMappingCheckLocalWrongOSPath: str = attr.ib(type=str)
    RemotePathMappingCheckRemoteDownloadClient: str = attr.ib(type=str)
    RemotePathMappingCheckWrongOSPath: str = attr.ib(type=str)
    RemotePathMappings: str = attr.ib(type=str)
    Remove: str = attr.ib(type=str)
    RemoveCompleted: str = attr.ib(type=str)
    RemoveCompletedDownloadsHelpText: str = attr.ib(type=str)
    RemovedFromTaskQueue: str = attr.ib(type=str)
    RemovedMovieCheckMultipleMessage: str = attr.ib(type=str)
    RemovedMovieCheckSingleMessage: str = attr.ib(type=str)
    RemoveDownloadsAlert: str = attr.ib(type=str)
    RemoveFailed: str = attr.ib(type=str)
    RemoveFailedDownloadsHelpText: str = attr.ib(type=str)
    RemoveFilter: str = attr.ib(type=str)
    RemoveFromBlocklist: str = attr.ib(type=str)
    RemoveFromDownloadClient: str = attr.ib(type=str)
    RemoveFromQueue: str = attr.ib(type=str)
    RemoveFromQueueText: str = attr.ib(type=str)
    RemoveHelpTextWarning: str = attr.ib(type=str)
    RemoveMovieAndDeleteFiles: str = attr.ib(type=str)
    RemoveMovieAndKeepFiles: str = attr.ib(type=str)
    RemoveRootFolder: str = attr.ib(type=str)
    RemoveSelected: str = attr.ib(type=str)
    RemoveSelectedItem: str = attr.ib(type=str)
    RemoveSelectedItems: str = attr.ib(type=str)
    RemoveSelectedMessageText: str = attr.ib(type=str)
    RemoveTagExistingTag: str = attr.ib(type=str)
    RemoveTagRemovingTag: str = attr.ib(type=str)
    RemovingTag: str = attr.ib(type=str)
    RenameBooks: str = attr.ib(type=str)
    RenameBooksHelpText: str = attr.ib(type=str)
    Renamed: str = attr.ib(type=str)
    RenameFiles: str = attr.ib(type=str)
    RenameMovies: str = attr.ib(type=str)
    RenameMoviesHelpText: str = attr.ib(type=str)
    Reorder: str = attr.ib(type=str)
    Replace: str = attr.ib(type=str)
    ReplaceIllegalCharacters: str = attr.ib(type=str)
    ReplaceIllegalCharactersHelpText: str = attr.ib(type=str)
    ReplaceWithDash: str = attr.ib(type=str)
    ReplaceWithSpaceDash: str = attr.ib(type=str)
    ReplaceWithSpaceDashSpace: str = attr.ib(type=str)
    Required: str = attr.ib(type=str)
    RequiredHelpText: str = attr.ib(type=str)
    RequiredPlaceHolder: str = attr.ib(type=str)
    RequiredRestrictionHelpText: str = attr.ib(type=str)
    RequiredRestrictionPlaceHolder: str = attr.ib(type=str)
    RescanAfterRefreshHelpText: str = attr.ib(type=str)
    RescanAfterRefreshHelpTextWarning: str = attr.ib(type=str)
    RescanAuthorFolderAfterRefresh: str = attr.ib(type=str)
    RescanMovieFolderAfterRefresh: str = attr.ib(type=str)
    Reset: str = attr.ib(type=str)
    ResetAPIKey: str = attr.ib(type=str)
    ResetAPIKeyMessageText: str = attr.ib(type=str)
    Restart: str = attr.ib(type=str)
    RestartNow: str = attr.ib(type=str)
    RestartRadarr: str = attr.ib(type=str)
    RestartReadarr: str = attr.ib(type=str)
    RestartReloadNote: str = attr.ib(type=str)
    RestartRequiredHelpTextWarning: str = attr.ib(type=str)
    Restore: str = attr.ib(type=str)
    RestoreBackup: str = attr.ib(type=str)
    Restrictions: str = attr.ib(type=str)
    Result: str = attr.ib(type=str)
    Retention: str = attr.ib(type=str)
    RetentionHelpText: str = attr.ib(type=str)
    RetryingDownloadInterp: str = attr.ib(type=str)
    RootFolder: str = attr.ib(type=str)
    RootFolderCheckMultipleMessage: str = attr.ib(type=str)
    RootFolderCheckSingleMessage: str = attr.ib(type=str)
    RootFolderPathHelpText: str = attr.ib(type=str)
    RootFolders: str = attr.ib(type=str)
    RSS: str = attr.ib(type=str)
    RSSIsNotSupportedWithThisIndexer: str = attr.ib(type=str)
    RSSSync: str = attr.ib(type=str)
    RSSSyncInterval: str = attr.ib(type=str)
    RssSyncIntervalHelpText: str = attr.ib(type=str)
    RSSSyncIntervalHelpTextWarning: str = attr.ib(type=str)
    Runtime: str = attr.ib(type=str)
    Save: str = attr.ib(type=str)
    SaveChanges: str = attr.ib(type=str)
    SaveSettings: str = attr.ib(type=str)
    SceneInformation: str = attr.ib(type=str)
    SceneNumberHasntBeenVerifiedYet: str = attr.ib(type=str)
    Scheduled: str = attr.ib(type=str)
    Score: str = attr.ib(type=str)
    Script: str = attr.ib(type=str)
    ScriptPath: str = attr.ib(type=str)
    Search: str = attr.ib(type=str)
    SearchAll: str = attr.ib(type=str)
    SearchBook: str = attr.ib(type=str)
    SearchBoxPlaceHolder: str = attr.ib(type=str)
    SearchCutoffUnmet: str = attr.ib(type=str)
    SearchFailedPleaseTryAgainLater: str = attr.ib(type=str)
    SearchFiltered: str = attr.ib(type=str)
    SearchForAllCutoffUnmetBooks: str = attr.ib(type=str)
    SearchForAllMissingBooks: str = attr.ib(type=str)
    SearchForMissing: str = attr.ib(type=str)
    SearchForMonitoredBooks: str = attr.ib(type=str)
    SearchForMovie: str = attr.ib(type=str)
    SearchForNewItems: str = attr.ib(type=str)
    SearchMissing: str = attr.ib(type=str)
    SearchMonitored: str = attr.ib(type=str)
    SearchMovie: str = attr.ib(type=str)
    SearchOnAdd: str = attr.ib(type=str)
    SearchOnAddHelpText: str = attr.ib(type=str)
    SearchSelected: str = attr.ib(type=str)
    Season: str = attr.ib(type=str)
    Seconds: str = attr.ib(type=str)
    Security: str = attr.ib(type=str)
    Seeders: str = attr.ib(type=str)
    SelectAll: str = attr.ib(type=str)
    SelectDotDot: str = attr.ib(type=str)
    SelectedCountAuthorsSelectedInterp: str = attr.ib(type=str)
    SelectedCountBooksSelectedInterp: str = attr.ib(type=str)
    SelectFolder: str = attr.ib(type=str)
    SelectLanguage: str = attr.ib(type=str)
    SelectLanguages: str = attr.ib(type=str)
    SelectMovie: str = attr.ib(type=str)
    SelectQuality: str = attr.ib(type=str)
    SelectReleaseGroup: str = attr.ib(type=str)
    SendAnonymousUsageData: str = attr.ib(type=str)
    SendMetadataToCalibre: str = attr.ib(type=str)
    Series: str = attr.ib(type=str)
    SeriesNumber: str = attr.ib(type=str)
    SeriesTotal: str = attr.ib(type=str)
    SetPermissions: str = attr.ib(type=str)
    SetPermissionsLinuxHelpText: str = attr.ib(type=str)
    SetPermissionsLinuxHelpTextWarning: str = attr.ib(type=str)
    SetReleaseGroup: str = attr.ib(type=str)
    SetTags: str = attr.ib(type=str)
    Settings: str = attr.ib(type=str)
    SettingsEnableColorImpairedMode: str = attr.ib(type=str)
    SettingsEnableColorImpairedModeHelpText: str = attr.ib(type=str)
    SettingsFirstDayOfWeek: str = attr.ib(type=str)
    SettingsLongDateFormat: str = attr.ib(type=str)
    SettingsRemotePathMappingHostHelpText: str = attr.ib(type=str)
    SettingsRemotePathMappingLocalPath: str = attr.ib(type=str)
    SettingsRemotePathMappingLocalPathHelpText: str = attr.ib(type=str)
    SettingsRemotePathMappingRemotePath: str = attr.ib(type=str)
    SettingsRemotePathMappingRemotePathHelpText: str = attr.ib(type=str)
    SettingsRuntimeFormat: str = attr.ib(type=str)
    SettingsShortDateFormat: str = attr.ib(type=str)
    SettingsShowRelativeDates: str = attr.ib(type=str)
    SettingsShowRelativeDatesHelpText: str = attr.ib(type=str)
    SettingsTimeFormat: str = attr.ib(type=str)
    SettingsWeekColumnHeader: str = attr.ib(type=str)
    SettingsWeekColumnHeaderHelpText: str = attr.ib(type=str)
    ShortDateFormat: str = attr.ib(type=str)
    ShouldMonitorExisting: str = attr.ib(type=str)
    ShouldMonitorExistingHelpText: str = attr.ib(type=str)
    ShouldMonitorHelpText: str = attr.ib(type=str)
    ShouldSearchHelpText: str = attr.ib(type=str)
    ShowAdvanced: str = attr.ib(type=str)
    ShowAsAllDayEvents: str = attr.ib(type=str)
    ShowBanners: str = attr.ib(type=str)
    ShowBannersHelpText: str = attr.ib(type=str)
    ShowBookCount: str = attr.ib(type=str)
    ShowBookTitleHelpText: str = attr.ib(type=str)
    ShowCertification: str = attr.ib(type=str)
    ShowCinemaRelease: str = attr.ib(type=str)
    showCinemaReleaseHelpText: str = attr.ib(type=str)
    ShowCutoffUnmetIconHelpText: str = attr.ib(type=str)
    ShowDateAdded: str = attr.ib(type=str)
    ShowGenres: str = attr.ib(type=str)
    ShowLastBook: str = attr.ib(type=str)
    ShowMonitored: str = attr.ib(type=str)
    ShowMonitoredHelpText: str = attr.ib(type=str)
    ShowMovieInformation: str = attr.ib(type=str)
    ShowMovieInformationHelpText: str = attr.ib(type=str)
    ShownAboveEachColumnWhenWeekIsTheActiveView: str = attr.ib(type=str)
    ShowName: str = attr.ib(type=str)
    ShownClickToHide: str = attr.ib(type=str)
    ShowPath: str = attr.ib(type=str)
    ShowQualityProfile: str = attr.ib(type=str)
    ShowQualityProfileHelpText: str = attr.ib(type=str)
    ShowRatings: str = attr.ib(type=str)
    ShowRelativeDates: str = attr.ib(type=str)
    ShowRelativeDatesHelpText: str = attr.ib(type=str)
    ShowReleaseDate: str = attr.ib(type=str)
    ShowReleaseDateHelpText: str = attr.ib(type=str)
    ShowSearch: str = attr.ib(type=str)
    ShowSearchActionHelpText: str = attr.ib(type=str)
    ShowSearchHelpText: str = attr.ib(type=str)
    ShowSizeOnDisk: str = attr.ib(type=str)
    ShowStudio: str = attr.ib(type=str)
    ShowTitle: str = attr.ib(type=str)
    ShowTitleHelpText: str = attr.ib(type=str)
    ShowUnknownAuthorItems: str = attr.ib(type=str)
    ShowUnknownMovieItems: str = attr.ib(type=str)
    ShowYear: str = attr.ib(type=str)
    Shutdown: str = attr.ib(type=str)
    Size: str = attr.ib(type=str)
    SizeLimit: str = attr.ib(type=str)
    SizeOnDisk: str = attr.ib(type=str)
    SkipBooksWithMissingReleaseDate: str = attr.ib(type=str)
    SkipBooksWithNoISBNOrASIN: str = attr.ib(type=str)
    SkipFreeSpaceCheck: str = attr.ib(type=str)
    SkipFreeSpaceCheckWhenImportingHelpText: str = attr.ib(type=str)
    SkipPartBooksAndSets: str = attr.ib(type=str)
    SkipRedownload: str = attr.ib(type=str)
    SkipredownloadHelpText: str = attr.ib(type=str)
    SkipSecondarySeriesBooks: str = attr.ib(type=str)
    Small: str = attr.ib(type=str)
    Socks4: str = attr.ib(type=str)
    Socks5: str = attr.ib(type=str)
    SomeResultsHiddenFilter: str = attr.ib(type=str)
    SorryThatAuthorCannotBeFound: str = attr.ib(type=str)
    SorryThatBookCannotBeFound: str = attr.ib(type=str)
    SorryThatMovieCannotBeFound: str = attr.ib(type=str)
    Sort: str = attr.ib(type=str)
    Source: str = attr.ib(type=str)
    SourcePath: str = attr.ib(type=str)
    SourceRelativePath: str = attr.ib(type=str)
    SourceTitle: str = attr.ib(type=str)
    SpecificBook: str = attr.ib(type=str)
    SqliteVersionCheckUpgradeRequiredMessage: str = attr.ib(type=str)
    SSLCertPassword: str = attr.ib(type=str)
    SslCertPasswordHelpText: str = attr.ib(type=str)
    SSLCertPasswordHelpText: str = attr.ib(type=str)
    SslCertPasswordHelpTextWarning: str = attr.ib(type=str)
    SSLCertPath: str = attr.ib(type=str)
    SslCertPathHelpText: str = attr.ib(type=str)
    SSLCertPathHelpText: str = attr.ib(type=str)
    SslCertPathHelpTextWarning: str = attr.ib(type=str)
    SSLPort: str = attr.ib(type=str)
    SslPortHelpTextWarning: str = attr.ib(type=str)
    StandardBookFormat: str = attr.ib(type=str)
    StandardMovieFormat: str = attr.ib(type=str)
    StartImport: str = attr.ib(type=str)
    StartProcessing: str = attr.ib(type=str)
    StartSearchForMissingMovie: str = attr.ib(type=str)
    StartTypingOrSelectAPathBelow: str = attr.ib(type=str)
    StartupDirectory: str = attr.ib(type=str)
    Status: str = attr.ib(type=str)
    StatusEndedContinuing: str = attr.ib(type=str)
    StatusEndedDeceased: str = attr.ib(type=str)
    StatusEndedEnded: str = attr.ib(type=str)
    Studio: str = attr.ib(type=str)
    Style: str = attr.ib(type=str)
    SubfolderWillBeCreatedAutomaticallyInterp: str = attr.ib(type=str)
    SuccessMyWorkIsDoneNoFilesToRename: str = attr.ib(type=str)
    SuccessMyWorkIsDoneNoFilesToRetag: str = attr.ib(type=str)
    SuggestTranslationChange: str = attr.ib(type=str)
    Sunday: str = attr.ib(type=str)
    SupportsRssvalueRSSIsNotSupportedWithThisIndexer: str = attr.ib(type=str)
    SupportsSearchvalueSearchIsNotSupportedWithThisIndexer: str = attr.ib(type=str)
    SupportsSearchvalueWillBeUsedWhenAutomaticSearchesArePerformedViaTheUIOrByReadarr: str = attr.ib(
        type=str
    )
    SupportsSearchvalueWillBeUsedWhenInteractiveSearchIsUsed: str = attr.ib(type=str)
    System: str = attr.ib(type=str)
    SystemTimeCheckMessage: str = attr.ib(type=str)
    Table: str = attr.ib(type=str)
    TableOptions: str = attr.ib(type=str)
    TableOptionsColumnsMessage: str = attr.ib(type=str)
    TagCannotBeDeletedWhileInUse: str = attr.ib(type=str)
    TagDetails: str = attr.ib(type=str)
    TagIsNotUsedAndCanBeDeleted: str = attr.ib(type=str)
    Tags: str = attr.ib(type=str)
    TagsHelpText: str = attr.ib(type=str)
    TagsSettingsSummary: str = attr.ib(type=str)
    Tasks: str = attr.ib(type=str)
    TaskUserAgentTooltip: str = attr.ib(type=str)
    TBA: str = attr.ib(type=str)
    Term: str = attr.ib(type=str)
    Test: str = attr.ib(type=str)
    TestAll: str = attr.ib(type=str)
    TestAllClients: str = attr.ib(type=str)
    TestAllIndexers: str = attr.ib(type=str)
    TestAllLists: str = attr.ib(type=str)
    TheAuthorFolderAndAllOfItsContentWillBeDeleted: str = attr.ib(type=str)
    TheBooksFilesWillBeDeleted: str = attr.ib(type=str)
    TheFollowingFilesWillBeDeleted: str = attr.ib(type=str)
    TheLogLevelDefault: str = attr.ib(type=str)
    ThisCannotBeCancelled: str = attr.ib(type=str)
    ThisConditionMatchesUsingRegularExpressions: str = attr.ib(type=str)
    ThisWillApplyToAllIndexersPleaseFollowTheRulesSetForthByThem: str = attr.ib(
        type=str
    )
    Time: str = attr.ib(type=str)
    TimeFormat: str = attr.ib(type=str)
    Timeleft: str = attr.ib(type=str)
    Title: str = attr.ib(type=str)
    Titles: str = attr.ib(type=str)
    TMDb: str = attr.ib(type=str)
    TMDBId: str = attr.ib(type=str)
    TmdbIdHelpText: str = attr.ib(type=str)
    TmdbRating: str = attr.ib(type=str)
    TmdbVotes: str = attr.ib(type=str)
    Today: str = attr.ib(type=str)
    Tomorrow: str = attr.ib(type=str)
    TooManyBooks: str = attr.ib(type=str)
    TorrentDelay: str = attr.ib(type=str)
    TorrentDelayHelpText: str = attr.ib(type=str)
    TorrentDelayTime: str = attr.ib(type=str)
    Torrents: str = attr.ib(type=str)
    TorrentsDisabled: str = attr.ib(type=str)
    TotalBookCountBooksTotalBookFileCountBooksWithFilesInterp: str = attr.ib(type=str)
    TotalFileSize: str = attr.ib(type=str)
    TotalSpace: str = attr.ib(type=str)
    Trace: str = attr.ib(type=str)
    TrackNumber: str = attr.ib(type=str)
    TrackTitle: str = attr.ib(type=str)
    Trailer: str = attr.ib(type=str)
    Trakt: str = attr.ib(type=str)
    Trigger: str = attr.ib(type=str)
    Type: str = attr.ib(type=str)
    UI: str = attr.ib(type=str)
    UILanguage: str = attr.ib(type=str)
    UILanguageHelpText: str = attr.ib(type=str)
    UILanguageHelpTextWarning: str = attr.ib(type=str)
    UISettings: str = attr.ib(type=str)
    UISettingsSummary: str = attr.ib(type=str)
    UnableToAddANewConditionPleaseTryAgain: str = attr.ib(type=str)
    UnableToAddANewCustomFormatPleaseTryAgain: str = attr.ib(type=str)
    UnableToAddANewDownloadClientPleaseTryAgain: str = attr.ib(type=str)
    UnableToAddANewImportListExclusionPleaseTryAgain: str = attr.ib(type=str)
    UnableToAddANewIndexerPleaseTryAgain: str = attr.ib(type=str)
    UnableToAddANewListExclusionPleaseTryAgain: str = attr.ib(type=str)
    UnableToAddANewListPleaseTryAgain: str = attr.ib(type=str)
    UnableToAddANewMetadataProfilePleaseTryAgain: str = attr.ib(type=str)
    UnableToAddANewNotificationPleaseTryAgain: str = attr.ib(type=str)
    UnableToAddANewQualityProfilePleaseTryAgain: str = attr.ib(type=str)
    UnableToAddANewRemotePathMappingPleaseTryAgain: str = attr.ib(type=str)
    UnableToAddANewRootFolderPleaseTryAgain: str = attr.ib(type=str)
    UnableToAddRootFolder: str = attr.ib(type=str)
    UnableToImportCheckLogs: str = attr.ib(type=str)
    UnableToLoadAltTitle: str = attr.ib(type=str)
    UnableToLoadBackups: str = attr.ib(type=str)
    UnableToLoadBlocklist: str = attr.ib(type=str)
    UnableToLoadCustomFormats: str = attr.ib(type=str)
    UnableToLoadDelayProfiles: str = attr.ib(type=str)
    UnableToLoadDownloadClientOptions: str = attr.ib(type=str)
    UnableToLoadDownloadClients: str = attr.ib(type=str)
    UnableToLoadGeneralSettings: str = attr.ib(type=str)
    UnableToLoadHistory: str = attr.ib(type=str)
    UnableToLoadImportListExclusions: str = attr.ib(type=str)
    UnableToLoadIndexerOptions: str = attr.ib(type=str)
    UnableToLoadIndexers: str = attr.ib(type=str)
    UnableToLoadLanguages: str = attr.ib(type=str)
    UnableToLoadListExclusions: str = attr.ib(type=str)
    UnableToLoadListOptions: str = attr.ib(type=str)
    UnableToLoadLists: str = attr.ib(type=str)
    UnableToLoadManualImportItems: str = attr.ib(type=str)
    UnableToLoadMediaManagementSettings: str = attr.ib(type=str)
    UnableToLoadMetadata: str = attr.ib(type=str)
    UnableToLoadMetadataProfiles: str = attr.ib(type=str)
    UnableToLoadMetadataProviderSettings: str = attr.ib(type=str)
    UnableToLoadMovies: str = attr.ib(type=str)
    UnableToLoadNamingSettings: str = attr.ib(type=str)
    UnableToLoadNotifications: str = attr.ib(type=str)
    UnableToLoadQualities: str = attr.ib(type=str)
    UnableToLoadQualityDefinitions: str = attr.ib(type=str)
    UnableToLoadQualityProfiles: str = attr.ib(type=str)
    UnableToLoadReleaseProfiles: str = attr.ib(type=str)
    UnableToLoadRemotePathMappings: str = attr.ib(type=str)
    UnableToLoadRestrictions: str = attr.ib(type=str)
    UnableToLoadResultsIntSearch: str = attr.ib(type=str)
    UnableToLoadRootFolders: str = attr.ib(type=str)
    UnableToLoadTags: str = attr.ib(type=str)
    UnableToLoadTheCalendar: str = attr.ib(type=str)
    UnableToLoadUISettings: str = attr.ib(type=str)
    UnableToUpdateRadarrDirectly: str = attr.ib(type=str)
    Unavailable: str = attr.ib(type=str)
    Ungroup: str = attr.ib(type=str)
    Unlimited: str = attr.ib(type=str)
    UnmappedFiles: str = attr.ib(type=str)
    UnmappedFilesOnly: str = attr.ib(type=str)
    UnmappedFolders: str = attr.ib(type=str)
    Unmonitored: str = attr.ib(type=str)
    UnmonitoredHelpText: str = attr.ib(type=str)
    Unreleased: str = attr.ib(type=str)
    UnsavedChanges: str = attr.ib(type=str)
    UnselectAll: str = attr.ib(type=str)
    UpdateAll: str = attr.ib(type=str)
    UpdateAutomaticallyHelpText: str = attr.ib(type=str)
    UpdateAvailable: str = attr.ib(type=str)
    UpdateCheckStartupNotWritableMessage: str = attr.ib(type=str)
    UpdateCheckStartupTranslocationMessage: str = attr.ib(type=str)
    UpdateCheckUINotWritableMessage: str = attr.ib(type=str)
    UpdateCovers: str = attr.ib(type=str)
    UpdateCoversHelpText: str = attr.ib(type=str)
    UpdateMechanismHelpText: str = attr.ib(type=str)
    Updates: str = attr.ib(type=str)
    UpdateScriptPathHelpText: str = attr.ib(type=str)
    UpdateSelected: str = attr.ib(type=str)
    UpdatingIsDisabledInsideADockerContainerUpdateTheContainerImageInstead: str = (
        attr.ib(type=str)
    )
    UpgradeAllowedHelpText: str = attr.ib(type=str)
    UpgradesAllowed: str = attr.ib(type=str)
    UpgradeUntilCustomFormatScore: str = attr.ib(type=str)
    UpgradeUntilQuality: str = attr.ib(type=str)
    UpgradeUntilThisQualityIsMetOrExceeded: str = attr.ib(type=str)
    UpperCase: str = attr.ib(type=str)
    Uptime: str = attr.ib(type=str)
    URLBase: str = attr.ib(type=str)
    UrlBaseHelpText: str = attr.ib(type=str)
    UrlBaseHelpTextWarning: str = attr.ib(type=str)
    UseCalibreContentServer: str = attr.ib(type=str)
    UseHardlinksInsteadOfCopy: str = attr.ib(type=str)
    Usenet: str = attr.ib(type=str)
    UsenetDelay: str = attr.ib(type=str)
    UsenetDelayHelpText: str = attr.ib(type=str)
    UsenetDelayTime: str = attr.ib(type=str)
    UsenetDisabled: str = attr.ib(type=str)
    UseProxy: str = attr.ib(type=str)
    Username: str = attr.ib(type=str)
    UsernameHelpText: str = attr.ib(type=str)
    UseSSL: str = attr.ib(type=str)
    UseSslHelpText: str = attr.ib(type=str)
    UsingExternalUpdateMechanismBranchToUseToUpdateReadarr: str = attr.ib(type=str)
    UsingExternalUpdateMechanismBranchUsedByExternalUpdateMechanism: str = attr.ib(
        type=str
    )
    Version: str = attr.ib(type=str)
    VersionUpdateText: str = attr.ib(type=str)
    VideoCodec: str = attr.ib(type=str)
    View: str = attr.ib(type=str)
    VisitGithubCustomFormatsAphrodite: str = attr.ib(type=str)
    WaitingToImport: str = attr.ib(type=str)
    WaitingToProcess: str = attr.ib(type=str)
    Wanted: str = attr.ib(type=str)
    Warn: str = attr.ib(type=str)
    WatchLibraryForChangesHelpText: str = attr.ib(type=str)
    WatchRootFoldersForFileChanges: str = attr.ib(type=str)
    Week: str = attr.ib(type=str)
    WeekColumnHeader: str = attr.ib(type=str)
    Weeks: str = attr.ib(type=str)
    WhatsNew: str = attr.ib(type=str)
    WhitelistedHardcodedSubsHelpText: str = attr.ib(type=str)
    WhitelistedSubtitleTags: str = attr.ib(type=str)
    Wiki: str = attr.ib(type=str)
    WouldYouLikeToRestoreBackup: str = attr.ib(type=str)
    WriteAudioTags: str = attr.ib(type=str)
    WriteAudioTagsScrub: str = attr.ib(type=str)
    WriteAudioTagsScrubHelp: str = attr.ib(type=str)
    WriteBookTagsHelpTextWarning: str = attr.ib(type=str)
    WriteTagsAll: str = attr.ib(type=str)
    WriteTagsNew: str = attr.ib(type=str)
    WriteTagsNo: str = attr.ib(type=str)
    WriteTagsSync: str = attr.ib(type=str)
    Year: str = attr.ib(type=str)
    Yes: str = attr.ib(type=str)
    YesCancel: str = attr.ib(type=str)
    YesMoveFiles: str = attr.ib(type=str)
    Yesterday: str = attr.ib(type=str)
    YouCanAlsoSearch: str = attr.ib(type=str)


@dataclass(init=False)
class _LogRecord(BaseModel):
    """Log record attributes."""

    exception: str = attr.ib(type=str)
    exceptionType: str = attr.ib(type=str)
    id: int = attr.ib(type=int)
    level: str = attr.ib(type=str)
    logger: str = attr.ib(type=str)
    message: str = attr.ib(type=str)
    time: datetime = attr.ib(type=datetime)


@dataclass(init=False)
class _QualityProfileItems(_Common3):
    """Quality profile items attributes."""

    allowed: bool = attr.ib(type=bool)
    items: list[_QualityProfileItems] | None = None
    quality: _QualityInfo = attr.ib(type=_QualityInfo)

    def __post_init__(self):
        self.items = [_QualityProfileItems(item) for item in self.items or []]
        self.quality = _QualityInfo(self.quality) or {}


@dataclass(init=False)
class _ReleaseCommon(BaseModel):
    """Release common attributes."""

    age: int = attr.ib(type=int)
    ageHours: float = attr.ib(type=float)
    ageMinutes: float = attr.ib(type=float)
    approved: bool = attr.ib(type=bool)
    commentUrl: str = attr.ib(type=str)
    downloadAllowed: bool = attr.ib(type=bool)
    downloadUrl: str = attr.ib(type=str)
    guid: str = attr.ib(type=str)
    indexer: str = attr.ib(type=str)
    indexerId: int = attr.ib(type=int)
    infoHash: str = attr.ib(type=str)
    infoUrl: str = attr.ib(type=str)
    leechers: int = attr.ib(type=int)
    magnetUrl: str = attr.ib(type=str)
    protocol: ProtocolType = attr.ib(type=ProtocolType)
    publishDate: datetime = attr.ib(type=datetime)
    qualityWeight: int = attr.ib(type=int)
    rejected: bool = attr.ib(type=bool)
    rejections: list[_Rejection] | None = None
    releaseWeight: int = attr.ib(type=int)
    sceneSource: bool = attr.ib(type=bool)
    seeders: int = attr.ib(type=int)
    size: int = attr.ib(type=int)
    temporarilyRejected: bool = attr.ib(type=bool)
    title: str = attr.ib(type=str)

    def __post_init__(self):
        """Post init."""
        self.rejections = [_Rejection(x) for x in self.rejections or []]


@dataclass(init=False)
class _RecordCommon(BaseModel):
    """Record common attributes."""

    page: int = attr.ib(type=int)
    pageSize: int = attr.ib(type=int)
    sortDirection: str = attr.ib(type=str)
    sortKey: str = attr.ib(type=str)
    totalRecords: int = attr.ib(type=int)


@dataclass(init=False)
class _ReleaseProfilePreferred(BaseModel):
    """Release profile preferred attributes."""

    key: str = attr.ib(type=str)
    value: int = attr.ib(type=int)


@dataclass(init=False)
class _Rename(BaseModel):
    """Rename attributes."""

    existingPath: str = attr.ib(type=str)
    newPath: str = attr.ib(type=str)


@dataclass(init=False)
class _Tag(BaseModel):
    """Tag attributes."""

    id: int = attr.ib(type=int)
    label: str = attr.ib(type=str)


@dataclass(init=False)
class _TagDetails(_Tag):
    """Tag details attributes."""

    delayProfileIds: list[int] = attr.ib(type='list[int]')
    importListIds: list[int] = attr.ib(type='list[int]')
    notificationIds: list[int] = attr.ib(type='list[int]')
    restrictionIds: list[int] = attr.ib(type='list[int]')


@dataclass(init=False)
class _UpdateChanges(BaseModel):
    """Update changes attributes."""

    fixed: list[str] = attr.ib(type='list[str]')
    new: list[str] = attr.ib(type='list[str]')


@dataclass(init=False)
class _TitleInfo(BaseModel):
    """Title info attributes."""

    title: str = attr.ib(type=str)
    titleWithoutYear: str = attr.ib(type=str)
    year: int = attr.ib(type=int)


@dataclass(init=False)
class _Notification(BaseModel):
    """Notification attributes."""

    configContract: str = attr.ib(type=str)
    implementation: str = attr.ib(type=str)
    implementationName: str = attr.ib(type=str)
    includeHealthWarnings: bool = attr.ib(type=bool)
    infoLink: str = attr.ib(type=str)
    onDownload: bool = attr.ib(type=bool)
    onGrab: bool = attr.ib(type=bool)
    onHealthIssue: bool = attr.ib(type=bool)
    onRename: bool = attr.ib(type=bool)
    onUpgrade: bool = attr.ib(type=bool)
    supportsOnDownload: bool = attr.ib(type=bool)
    supportsOnGrab: bool = attr.ib(type=bool)
    supportsOnHealthIssue: bool = attr.ib(type=bool)
    supportsOnRename: bool = attr.ib(type=bool)
    supportsOnUpgrade: bool = attr.ib(type=bool)
    tags: list[int] = attr.ib(type='list[int]')


@dataclass(init=False)
class _RetagChange(BaseModel):
    """Retag change attributes."""

    field: str = attr.ib(type=str)
    oldValue: str = attr.ib(type=str)
    newValue: str = attr.ib(type=str)


@dataclass(init=False)
class _HistoryCommon(BaseModel):
    """History common attributes."""

    age: int = attr.ib(type=int)
    ageHours: float = attr.ib(type=float)
    ageMinutes: float = attr.ib(type=float)
    downloadClientName: str = attr.ib(type=str)
    downloadUrl: str = attr.ib(type=str)
    droppedPath: str = attr.ib(type=str)
    fileId: int = attr.ib(type=int)
    importedPath: str = attr.ib(type=str)
    indexer: str = attr.ib(type=str)
    nzbInfoUrl: str = attr.ib(type=str)
    protocol: ProtocolType = attr.ib(type=ProtocolType)
    publishedDate: datetime = attr.ib(type=datetime)
    reason: str = attr.ib(type=str)
    releaseGroup: str = attr.ib(type=str)
    size: int = attr.ib(type=int)
    torrentInfoHash: str = attr.ib(type=str)


@dataclass(init=False)
class _HistoryData(_HistoryCommon):
    """History data attributes."""

    downloadClient: str = attr.ib(type=str)
    downloadForced: bool = attr.ib(type=bool)
    guid: str = attr.ib(type=str)


@dataclass(init=False)
class _QualityCommon(BaseModel):
    """Quality common attributes."""

    quality: _Quality = attr.ib(type=_Quality)
    qualityCutoffNotMet: bool = attr.ib(type=bool)

    def __post_init__(self):
        """Post init."""
        super().__post_init__()
        self.quality = _Quality(self.quality) or {}


@dataclass(init=False)
class _Ratings(BaseModel):
    """Ratings attributes."""

    value: float = attr.ib(type=float)
    votes: int = attr.ib(type=int)


@dataclass(init=False)
class _Link(BaseModel):
    """Link attributes."""

    name: str = attr.ib(type=str)
    url: str = attr.ib(type=str)


@dataclass(init=False)
class _StatusMessage(BaseModel):
    """Status message attributes."""

    messages: list[str] = attr.ib(type='list[str]')
    title: str = attr.ib(type=str)


@dataclass(init=False)
class _Editor(BaseModel):
    """Editor attributes."""

    applyTags: str = attr.ib(type=str)
    deleteFiles: bool = attr.ib(type=bool)
    minimumAvailability: str = attr.ib(type=str)
    monitored: bool = attr.ib(type=bool)
    moveFiles: bool = attr.ib(type=bool)
    qualityProfileId: int = attr.ib(type=int)
    rootFolderPath: str = attr.ib(type=str)
    tags: list[int] = attr.ib(type='list[int]')


@dataclass(init=False)
class _IsLoaded(BaseModel):
    """Is loaded attribute."""

    isLoaded: bool = attr.ib(type=bool)


@dataclass(init=False)
class _Rejection(BaseModel):
    """Rejection attributes."""

    reason: str = attr.ib(type=str)
    type: str = attr.ib(type=str)


@dataclass(init=False)
class _ManualImport(BaseModel):
    """Manual import attributes."""

    downloadId: str = attr.ib(type=str)
    id: int = attr.ib(type=int)
    name: str = attr.ib(type=str)
    path: str = attr.ib(type=str)
    quality: _Quality = attr.ib(type=_Quality)
    qualityWeight: int = attr.ib(type=int)
    rejections: list[_Rejection] | None = None
    size: int = attr.ib(type=int)

    def __post_init__(self):
        """Post init."""
        self.quality = _Quality(self.quality) or {}
        self.rejections = [_Rejection(x) for x in self.rejections or []]


@dataclass(init=False)
class _Monitor(BaseModel):
    """Sonarr series monitor attributes."""

    id: int = attr.ib(type=int)
    monitored: bool = attr.ib(type=bool)


@dataclass(init=False)
class _MonitorOption(BaseModel):
    """Sonarr series monitor option attributes."""

    monitor: str | None = None
